### ISSUE TITLE
context string management

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#101]
We're hitting the PRF pretty hard now for the various key derivation steps.  Now #100 adds context strings to the signature input on CertificateVerify.

It might not be necessary to go for a full-blown registry, but having a table for each of these might help ensure that we don't use the same string twice unintentionally.

**Comment by ekr** [comment]
I think we can live without a table here, and things are starting to get long... If you have a PR that actually shows this can be done briefly, I'll re-open.
