### ISSUE TITLE
move client_certificate_type into CertificateRequest + Certificate?

### ISSUE THREAD

**Issue by isonmad** [tlswg/tls13-spec#1012]
a6d173f0f8ca99ad99d07d09a26b6bb6ef504c13 was a mistake, but is there a reason why client_certificate_type should stay in the unencrypted ClientHello at all?

Although moving CCT out of the ClientHello would also remove the need for client_certificate_type and server_certificate_type to have different code points at all.

**Comment by martinthomson** [comment]
A single certificate_type extension would be preferable.

**Comment by kaduk** [comment]
We lose backwards compatibility to 1.2 and below if we move it.  Also it moves away from client-offer-server-pick negotiation, but I'm fine with that (and we're doing that a little already).
