### ISSUE TITLE
Inconsistency in Signature Algorithms/Schemes

### ISSUE THREAD

**Issue by jurajsomorovsky** [tlswg/tls13-spec#1029]
This is a minor editorial issue, found by implementing TLS1.3, with @ic0ns and @NErinola.

Section 4.2.3 of the current draft provides a list of Signature Algorithms / Signature Schemes: https://tlswg.github.io/tls13-spec/#rfc.section.4.2.3

The enums are created by two values (hash,signature), e.g.:
       /* RSASSA-PKCS1-v1_5 algorithms */
       rsa_pkcs1_sha256(0x0401),
       rsa_pkcs1_sha384(0x0501),
       rsa_pkcs1_sha512(0x0601),

The enums for RSA-PSS algorithms are inconsistent, their values are constructed as (signature, hash):
      /* RSASSA-PSS algorithms */
       rsa_pss_sha256(0x0804),
       rsa_pss_sha384(0x0805),
       rsa_pss_sha512(0x0806),`

It should be:
       /* RSASSA-PSS algorithms */
       rsa_pss_sha256(0x0408),
       rsa_pss_sha384(0x0508),
       rsa_pss_sha512(0x0608),

**Comment by ekr** [comment]
Actually, this is intentional. We are no longer using that construction. Its coincidental that they are inverted like this.

**Comment by jurajsomorovsky** [comment]
Ok, thank you for the clarification
