### ISSUE TITLE
Additional clarity about which messages are in session_hash

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#103]
WRT Pull Request #89, Martin Thomson writes.

"As I commented in the meeting, I think that we need to be somewhat more prescriptive about what is 
covered by the session_hash at each point. That is, enumerate precisely what messages form handshake_messages (and probably also what parts of those messages). This is useful since session_hash is used in two ways. It will be more relevant when we talk about 0 RTT handshakes, where the order of messages that appear in the handshake could change significantly."

**Comment by grubba** [comment]
Agreed. Section 8.1 of draft 4 is less than clear about at what point the session_hash is when the resumption_premaster_secret is generated. The second to last paragraph seems to imply that it is generated after both Finished messages, as it says that it differs from both the other hashes, but it should be made explicit.

**Comment by ekr** [comment]
The intention here is that the resumption and master secrets are generated using the same session hash and that hs _master_secret is generated with a different session hash. I'll see if I can rephrase, but if someone wants to send a PR that wouldn't be unappreciated.

**Comment by martinthomson** [comment]
> The intention here is that the resumption and master secrets are generated using the same session hash and that hs _master_secret is generated with a different session hash. I'll see if I can rephrase, but if someone wants to send a PR that wouldn't be unappreciated.

You might consider rephrasing that statement too.  My understanding is that session hash is a hash over the concatenated transcript of the handshake.  However, it is important to note that as we move to 0RTT modes, the order of message changes, though the actual messages are largely the same.  I consider it important to describe precisely what messages and in what order.

I imagine a formulation of the form:
```
session_hash = hash(transcript)
transcript = client_flight_1 || server_flight_1 || ... client_flight_2
client_flight_1 = client_hello (without the early data extension, maybe) || client_key_share
server_flight_1 = server_hello || server_key_share
```
etc...   will be helpful.

**Comment by grubba** [comment]
One possible way to add clarity with a minimum of ambiguity, would to add indications of where the master keys are generated to figures 1 through 3 in section 7.2, but the figures aren't normative, are they?

**Comment by grubba** [comment]
I just submitted a pull request along the above comment.

When preparing the change, I noticed some further strangeness. The draft says:

    Once the last non-Finished message has been sent, the client and
    server then compute the master secret which will be used for the
    remainder of the session:

This seems to indicate that the master secret should be computed before the server-side Finished message if no CertificateRequest was sent (as the client won't send any Certificate or CertificateVerify then), and after it if a CertificateRequest was sent. As far as I can see, this behavior would only make the code on both client and server more complicated for no benefit.

**Comment by ekr** [comment]
The advantage is that if there is no client auth then the server can start sending data immediately.

Note that there is no requirement that servers or clients do so, since the computation is the same if they do it at the end of the handshake.

**Comment by grubba** [comment]
Yes, but the server can do so anyway, since it knows what it will send in the Final message.

**Comment by ekr** [comment]
Correct. The problem is the client's Certificate, and following messages. So it's easiest to just not include any Finished messages at all.

**Comment by grubba** [comment]
Ie I don't see any inherent benefit in the server-side sequence

  ...
  Certificate
  CertificateVerify
  [Compute master_sequence]
  Finished
  [Switch to master_sequence derived keys]
  Application Data

over

  ...
  Certificate
  CertificateVerify
  Finished
  [Compute master_sequence]
  [Switch to master_sequence derived keys]
  Application Data

And the latter allows for common code for all cases if the server doesn't do early data.

**Comment by ekr** [comment]
Oh, I had misunderstood you. I don't disagree with this.

**Comment by grubba** [comment]
One more issue that needs clarification: If the server fails to validate the client Finished packet, should it send the alert complaining about it encrypted with the handshake key or the main key?

I suspect that the alert should be sent encrypted with the main key, as the client likely has switched to using the main key after sending its Finished packet.

**Comment by ekr** [comment]
This seems like it should be clearer now. Please file individual issued if needed.
