### ISSUE TITLE
Overlap of signature algorithms with different semantics

### ISSUE THREAD

**Issue by nmav** [tlswg/tls13-spec#1035]
TLS 1.3 section 4.2.3.  Signature Algorithms contains:
```
          /* ECDSA algorithms */
          ecdsa_secp256r1_sha256(0x0403),
          ecdsa_secp384r1_sha384(0x0503),
          ecdsa_secp521r1_sha512(0x0603),
```
These overlap with sha256(4), sha384(5), sha512(6) with ecdsa(3) from RFC5246, though they have different semantics to the level they can be considered different algorithms.

To overcome that inconsistency TLS 1.3 includes that text:

> If TLS 1.2 is negotiated, implementations MUST be prepared
> to accept a signature that uses any curve that they advertised in
> the "supported_groups" extension.

So the interpretation of this extension data can only happen after the TLS version is negotiated, because that's necessary to translate the code points to their actual meaning. Given that negotiation of TLS version is also done with an extension which can be present after the signature algorithms extension, that re-use feels like an unnecessary complication.

Is there a particular advantage of re-using the code points for the new signature algorithms in TLS 1.3? Wouldn't it make more sense to assign new code points to the new algorithms similarly to what it was done for RSA-PSS and thus eliminate any ambiguity?

**Comment by ekr** [comment]
There was consensus to do this, so you'll need to get consensus on the list to change it.
