### ISSUE TITLE
Re-start session hash and Finished hash in mismatched case

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#104]
See Figure 2,

"[[OPEN ISSUE: Do we restart the handshake hash?]]
[[OPEN ISSUE: We need to make sure that this flow doesn't introduce
downgrade issues. Potential options include continuing the handshake
hashes (as long as clients don't change their opinion of the server's
capabilities with aborted handshakes) and requiring the client to send
the same ClientHello (as is currently done) and then checking you get
the same negotiated parameters.]]"

Re-starting the hashes is conceptually cleaner, but needs security
analysis.

**Comment by enygren** [comment]
For the repeated ClientHello case (in the face of HelloRetryRequest), what about having HelloRetryRequest always contain a cookie (similar to in HelloVerifyRequest) and require repeated ClientHellos to replay that cookie.  If that cookie is an HMAC by the server across an key held by the server, any server extra data (client ip?), and the invariant part of the ClientHello, then the server can revalidate the ClientHello without needing to keep any state about it.  The handshake hash would contain the cookie (which includes an HMAC of the initial ClientHello that the server should revalidate against the new ClientHello).  This aligns well with DTLS HelloVerifyRequest and also allows the first ClientHello to be excluded from the handshake hash, and then makes things like DTLS and any future client-puzzles extension work fit in fairly cleanly.

**Comment by ekr** [comment]
I certainly think we want a cookie here because I want to merge HelloVerifyRequest and HelloRetryRequest. I'm less sure that the "verify that it was sent without changes" plan is practical, but it's certainly something we can explore.
