### ISSUE TITLE
resumption validation

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#1040]
2.3.  Zero-RTT Data says:

> -  The TLS version number for use with this PSK
> 
> -  The cipher suite for use with this PSK
> 
> -  The Application-Layer Protocol Negotiation (ALPN) protocol [RFC7301], if any is to be used
> 
> -  The Server Name Indication (SNI), if any is to be used

But 4.6.1.  New Session Ticket Message says:

> Any ticket MUST only be resumed with a cipher suite that has the same
> KDF hash algorithm as that used to establish the original connection,
> and only if the client provides the same SNI value as in the original
> connection, as described in Section 3 of [RFC6066].

For consistency, I would like to have the latter in Section 2.2 with the same style.

Moreover, I would like to know where this differences of requirements come from.

**Comment by kaduk** [comment]
I think 4.2.10 may be more appropriate than 2.2, as it is closer to where the server is doing the relevant processing.

**Comment by kazu-yamamoto** [comment]
Now 4.2.10 has clear requirements. So, why don't we remove the same requirement from 2.3?

> When clients use a PSK obtained externally to send early data, then the following
additional information MUST be provisioned to both parties:
>
> -  The TLS version number for use with this PSK
> 
> -  The cipher suite for use with this PSK
> 
> -  The Application-Layer Protocol Negotiation (ALPN) protocol [RFC7301], if any is to be used
> 
> -  The Server Name Indication (SNI), if any is to be used
