### ISSUE TITLE
Early data with external PSK

### ISSUE THREAD

**Issue by mattcaswell** [tlswg/tls13-spec#1043]
The Early Data Indication section contains this sentence:

    The parameters for the 0-RTT data (symmetric cipher suite, ALPN
    protocol, etc.) are the same as those which were negotiated in the
    connection which established the PSK.

This implies to me that you can only do 0-RTT where the PSK was established via an earlier connection. In external PSK this is not the case. I don't think this interpretation was the intention.

**Comment by kaduk** [comment]
This is stale text from before we allowed 0-RTT with external PSK, IIRC.
