### ISSUE TITLE
TLS-Exporter

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#1060]
The quic tls draft uses the `TLS-Exporter` function but it is not defined anywhere.
Section 7.5 should define `TLS-Exporter` as follows:

```
TLS-Exporter(label, context_value, key_length) =
    HKDF-Expand-Label(Derive-Secret(Secret, label, ""),
                         "exporter", Hash(context_value), key_length)
```

**Comment by kaduk** [comment]
> The exporter interface remains the same.

I'm not convinced we need to duplicate this line from RFC 5705.

**Comment by kazu-yamamoto** [comment]
RFC 5705 does not define `TLS-Exprter` explicitly, either.
So, the quic tls draft refers to a undefined function name.

**Comment by Lekensteyn** [comment]
The current version of ietf-quic-tls-07 (https://tools.ietf.org/html/draft-ietf-quic-tls-07#section-5.2) refers to 7.5 of ietf-tls-tls13-21. I would support adding the extra line to the TLS 1.3 draft as suggested by @kazu-yamamoto. At first I was also confused about the meaning of the (undefined) TLS-Exporter function until I started reading the preceding section more closely.
