### ISSUE TITLE
clarify role of TLS vs PKI library

### ISSUE THREAD

**Issue by kaduk** [tlswg/tls13-spec#1062]
Hubert says on the list:

> that disjoint between "stuff that TLS library is supposed to do" and 
"stuff that PKI library is supposed to do" could be spelled out more 
explicitly in the RFC though

**Comment by tomato42** [comment]
In particular, because of the way signature_schemes work, the PKI library must support a superset of signature algorithms of the TLS library

**Comment by ekr** [comment]
I think this is clear enough.

**Comment by ekr** [comment]
Moreover, it's not our job to specify how implementations are constructed.

**Comment by tomato42** [comment]
But it is our job to point out when there are possible integration or interoperability issues and which parts are necessary to get a secure implementation (see the whole appendix D or E).
