### ISSUE TITLE
Certificate message description doesn't define client behavior on unknown extensions

### ISSUE THREAD

**Issue by nmav** [tlswg/tls13-spec#1084]
The section `4.4.2.  Certificate`, says about extensions:
```
An extension MUST only be present in a Certificate message if the
corresponding ClientHello extension was presented in the initial handshake.
```

However it does not define what a client (or server) should do if they encounter an unknown extension from the peer. A common pattern across the other message extensions is to ignore it, though according to the text above one could also reject the message (but no alert message is specified for that).

**Comment by kaduk** [comment]
A client receiving a Certificate message with an extension that was not in the ClientHello ought to terminate the connection -- unknown extensions have unknown semantics.

The text should probably be tightened up for what extensions are allowed in a Certificate message from the client.

**Comment by davidben** [comment]
There is text common to all extension processing in 4.2:
https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.section.4.2

**Comment by nmav** [comment]
Thanks @davidben then, I think the text:
```
Implementations MUST NOT send extension responses if the remote endpoint did not send the corresponding extension requests, with the exception of the “cookie” extension in HelloRetryRequest. Upon receiving such an extension, an endpoint MUST abort the handshake with an “unsupported_extension” alert.
```
clarifies that. A minor suggestion for text clarity would be for the Certificate section to refer to extension processing for extension handling rules rather than defining a small part of them. I'm closing this issue as it is addressed.
