### ISSUE TITLE
Off-by-one error on the maximum record size

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#1087]
I had been using the text in [Section 5.4](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#record-padding):

> The presence of padding does not change the overall record size limitations - the full encoded TLSInnerPlaintext MUST not exceed 2^14 octets. 

But the text in the very last sentence of [Section 5.2](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#record-payload-protection) says:

>  This limit is derived from the maximum TLSPlaintext length of 2^14 octets + 1 octet for ContentType + the maximum AEAD expansion of 255 octets.

Which doesn't really make sense.  TLSPlaintext includes the record header as well as the encrypted data.  I suppose that this is accurate if it means `TLSPlaintext.length`, but I misread this as the entire length of the structure.  That's a minor point.

TLSInnerPlaintext can be at most 2^14 (as defined in Section 5.4), which leads to a different limit of 2^14-1 for TLSPlaintext.length.  Should we instead say that 2^14+256 is the limit and the AEAD expansion is 256 octets instead of 255?

Leading me to think that something along these lines is what should go in Section 5.2:

> An AEAD algorithm used in TLS 1.3 MUST NOT produce an expansion greater than 256 octets. An endpoint that receives a record from its peer with TLSCiphertext.length larger than 2^14 + 256 octets MUST terminate the connection with a “record_overflow” alert.  Similarly, an endpoint that receives a TLSInnerPlaintext that is more than 2^14 octets in total length MUST terminate the connection with a “record_overflow” alert.  This implies an upper limit of 2^14-1 on the value of TLSPlaintext.length.

Or something like that.

**Comment by Lekensteyn** [comment]
See #1083

**Comment by ekr** [comment]
Fixed
