### ISSUE TITLE
post_handshake_auth

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#1089]
The structure of `post_handshake_auth` is missing.

**Comment by kaduk** [comment]
> The "extension_data" field of the "post_handshake_auth" extension is zero
length.

**Comment by kazu-yamamoto** [comment]
OK. So, I would like to have either

```
Empty PostHandShakeAuth;
```

or 

```
struct {} PostHandShakeAuth;
```
explicitly.

**Comment by Lekensteyn** [comment]
@ekr not sure if you are getting notifications for the comments to commits, but as a nitpick:

> PostHand**s**hakeAuth

(Handshake is a single word)
