### ISSUE TITLE
Anti-replay mechanism

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#11]
A 0-RTT mode needs some sort of replay protection for both application data and any client credentials that might appear in the first flight from a client.

All mechanisms rely on some amount of server state, but differ in how they allow a server to limit the total state commitment.  There are plenty of options, each with their own trade-offs, we just need to pick one.

**Comment by ekr** [comment]
Decided at the Seattle Interim and Dallas IETF that it was impractical to fix this in the general case. Fixed to the extent we plan to fix it in -08
