### ISSUE TITLE
hello_retry_request vs hello_retry_request_RESERVED

### ISSUE THREAD

**Issue by Lekensteyn** [tlswg/tls13-spec#1101]
The text refers to hello_retry_request (e.g. in IANA considerations), but the HandshakeType enum refers to hello_retry_request_RESERVED.

Should something be said about Server Hello being able to modify `Handshake.msg_type`?
Should something be said about rejecting handshake messages with `msg_type=6`? (The current `switch (Handshake.msg_type)` seems to suggest that the wire can really contain 6.)

**Comment by kazu-yamamoto** [comment]
My syntax validator also detects this error. We need to fix this.

**Comment by kazu-yamamoto** [comment]
I guess that it is hard to express a nest `select`. So, it seems to me that a comment is reasonable:

```
       struct {
           select (Handshake.msg_type) {
               case client_hello:
                   KeyShareEntry client_shares<0..2^16-1>;
                /* NamedGroup selected_group; in the case of Hello Retry Request*/

               case server_hello:
                   KeyShareEntry server_share;
           };
       } KeyShare;
```

**Comment by Lekensteyn** [comment]
That comment is not easy to parse for a machine :/
(btw, the comment is for the server_hello case, not client_hello).

`select` is only defined for enumerations, so we cannot do something like:
```
struct {
    select (Handshake.msg_type) {
        case client_hello:
            KeyShareEntry client_shares<0..2^16-1>;

        case server_hello:
            select (ServerHello.random) {
                case hello_retry_request_magic:
                    NamedGroup selected_group;
                default:
                    KeyShareEntry server_share;
            };
    };
} KeyShare;
```
(and even the above is not accurate since interpretation of random depends on the supported_extensions value.)

Maybe something like:
```
struct {
    HandshakeType msg_type;
    ProtocolVersion real_version;
} HelloParameters;

struct {
    select (Handshake.msg_type) {
        case client_hello:
            KeyShareEntry client_shares<0..2^16-1>;

        case server_hello:
            select (ServerHelloParameters.msg_type) {
                case server_hello:
                    KeyShareEntry server_share;
                case hello_retry_request:
                    NamedGroup selected_group;
            };
    };
} KeyShare;
```

with the intention that ServerHelloParameters is populated while preparsing the SH message (prescan for supported_versions, detect HRR vs normal SH based on Random). This is inspired by the SecurityParameters type in RFC 5246.
