### ISSUE TITLE
Client Certificate extensions: SCT, OCSP Stapling

### ISSUE THREAD

**Issue by Lekensteyn** [tlswg/tls13-spec#1111]
status_request and signed_certificate_status timestamps are allowed in the CertificateRequest message according to https://tools.ietf.org/html/draft-ietf-tls-tls13-22#page-41

Certificate extensions (https://tools.ietf.org/html/draft-ietf-tls-tls13-22#page-66) however say:

>  An extension MUST only
>  be present in a Certificate message if the corresponding
>  ClientHello extension was presented in the initial handshake.

Is this also the intended behavior for client certificates, or should it instead require extensions to be advertised in CertificateRequest? (This is relevant for future extensions.)

No idea why a client would bother sending SCT or status_request extensions, but that is not forbidden by the TLS 1.3 spec. The status_request (RFC 6066) and [SCT](https://tools.ietf.org/html/rfc6962#section-3.3.1) extensions are written such that it seems unusable in client certs though.

**Comment by tomato42** [comment]
I'd say it's both - for those extensions to be in client side Certificate message they need to be both in Client Hello and in Certificate Request.

That's because any extensions in Certificate Request must have been first advertised in Client Hello

**Comment by ekr** [comment]
That's not correct. You can advertise stuff in CR that's not in CH (e.g.,
X.509 OIDs). Peter, good catch. PR welcome.

**Comment by tomato42** [comment]
@ekr that's rather ugly - to this point only the cookie extension was of a "you support it even if you advertise it", I don't like adding more exceptions to that rule...

**Comment by ekr** [comment]
It's been this way for some time. https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#extensions

```
Extensions are generally structured in a request/response fashion, though some extensions are just indications with no corresponding response. The client sends its extension requests in the ClientHello message and the server sends its extension responses in the ServerHello, EncryptedExtensions, HelloRetryRequest and Certificate messages. The server sends extension requests in the CertificateRequest message which a client MAY respond to with a Certificate message. The server MAY also send unsolicited extensions in the NewSessionTicket, though the client does not respond directly to these.```

**Comment by davidben** [comment]
It's much simpler this way. As in the text EKR pointed to, extensions come in request/response pairs, so there is only one kind of flow to worry about. In your version, client certificate extensions have this weird three-phase bit which ends up meaning extra logic in implementations.

This additionally is more flexible. Suppose I am willing to send an SCT on my client certificate, but I don't have anything useful to do with the server one. (The inverse is more likely for SCTs but consider a future bit of certificate metadata.) In your version, there is no way to distinguish "I want an SCT" from "I won't explode if you request one of me".

**Comment by tomato42** [comment]
> The server sends extension requests in the CertificateRequest message which a client MAY respond to with a Certificate message. The server MAY also send unsolicited extensions in the NewSessionTicket, though the client does not respond directly to these.

That's what I meant - the Certificate Request ones are not described as "unsolicited".

> In your version, there is no way to distinguish "I want an SCT" from "I won't explode if you request one of me".

I don't think this is a useful extension to make. But I digress.

If we make all Certificate Request extensions unsolicited, that's fine by me. But I think that it's a significant change from TLS 1.2, and should be documented as such.

**Comment by Lekensteyn** [comment]
TLS 1.2 had no extension mechanism for CertificateRequest: https://tools.ietf.org/html/rfc5246#section-7.4.4

**Comment by davidben** [comment]
CertificateRequest extensions were intended to be unsolicited, yeah.
