### ISSUE TITLE
Clarification: outer record type checking

### ISSUE THREAD

**Issue by tmthrgd** [tlswg/tls13-spec#1127]
In cloudflare/tls-tris#47 the question of whether the `opaque_type` field should be validated was raised.
> It has no MUST requirement on the receiver, so not sure if we should check it or not.

https://tools.ietf.org/html/draft-ietf-tls-tls13-22#section-5.2 says:
> opaque_type
>    The outer opaque_type field of a TLSCiphertext record is always set to the value 23 (application_data) for outward compatibility with middleboxes accustomed to parsing previous versions of TLS. The actual content type of the record is found in TLSInnerPlaintext.type after decryption.

Currently the draft implementation in BoringSSL [aborts the connection with a decode_error alert](https://github.com/google/boringssl/blob/0a54e998481b0b5a8abd9717c5f7301a3b18b628/ssl/tls_record.cc#L326-L331) if the type is not application_data. While the draft implementation in cloudflare/tls-tris simply [ignores the outer record type](https://github.com/cloudflare/tls-tris/blob/8db472667bf6426b18b528f0225fa58ec5e16a6f/conn.go#L754-L772) without checking it.

This seems like a small point the specification should be clearer on. I'd suggest explicitly stating whether opaque_type must be checked (as per BoringSSL) or must be ignored (as per tls-tris).

/cc @Lekensteyn

**Comment by kaduk** [comment]
This sort of question tends to fall into a category where only a pragmatic answer is reasonable, namely that we can only enforce strict requirements once it is known that TLS 1.3 is definitively in use, which is the case here.  But I am not entirely convinced that there is value in having a normative behavior in the spec; one could make reasonable arguments for a given implementation to go either way, and the question is irrelevant for the question of whether two compliant implementations will interoprate, so it seems just to be a venue for potential disagreement with no real upside.

**Comment by tmthrgd** [comment]
@kaduk Easy, thanks for the prompt reply. This can be considered closed then.
