### ISSUE TITLE
Be more clear about "cryptographic security" goal

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#114]
The doc says:

"The goals of the TLS protocol, in order of priority, are as follows:

1. Cryptographic security: TLS should be used to establish a secure connection
between two parties."

This is pretty handwavy. We should be a little more clear about the target and
then point to a security considerations section which has more detail about the
desired properties.

**Comment by beurdouche** [comment]
Do you have something stashed somewhere already ? =)

**Comment by beurdouche** [comment]
Should we draft something here ?

**Comment by ekr** [comment]
This has been updated in a recent versio
