### ISSUE TITLE
Draft Status

### ISSUE THREAD

**Issue by geraldsnm** [tlswg/tls13-spec#1140]
Is there a target date for when TLS1.3 will be a formalized protocol? It seems it's been in draft forever, and there were comments on the OpenSSL forums that they were targetting TLS1.3 support in the 2nd quarter of 2017 (I believe they were looking at adding TLS1.3 to OpenSSL 1.1 but the one caveat is they were expecting it to be out of draft by that time otherwise they were still putting off including support.

So is there a target date for a completed TLS 1.3 or at least a release candidate?

**Comment by Lekensteyn** [comment]
The spec is going through its third WGLC, and unless there is a major issue, it should be finalized soon.

https://www.ietf.org/mail-archive/web/tls/current/msg25263.html

(I guess you can consider all WGLCs as "release candidate", but of course it is not identical to a final RFC.)

**Comment by Henrocker** [comment]
Any update since the meeting on the 26th?

**Comment by seanturner** [comment]
The draft has completed its 3rd WGLC.  -24 was just published and I've moved it to Publication Requested.  This means that it'll now enter the IETF LC process.
