### ISSUE TITLE
Require signature_algorithms extension.

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#116]
We should just require it.

**Comment by beurdouche** [comment]
I agree with that, it goes with potentially deleting the SignatureAlgorithm from the new ciphersuites.
By the way, shouldn't we consider also removing MD5 from HashAlgorithms even if it is used a lot 
(I don't know the numbers on that ...) ?

**Comment by davegarrett** [comment]
PR #201 mandates usage of this extension and also adds an explicit error expectation for MD5 (it's already listed as deprecated in the current draft).

**Comment by davegarrett** [comment]
@ekr: This should be closable now.
