### ISSUE TITLE
Remove the glossary?

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#117]
Is this helping?

**Comment by seanturner** [comment]
I'm in favor of removing the glossary.  I don't think there's any need to explain what AES, DSA, etc. is in this document.  Maybe it was needed when it first came out but it's not needed now.  The only definition I thought might be needed is application layer/application layer protocol, but if you read s1 (right before where these terms will go) the concepts of layering on top of TLS is explained well enough in my mind.  I could see adding a definition for "resumption" though.

**Comment by richsalz** [comment]
Define resumption in-line with the text when it is first used, maybe.  But I like Dave's change.

**Comment by seanturner** [comment]
I can live with that too.  Having it defined will hopefully stop these kind of things:
https://datatracker.ietf.org/liaison/1363/

**Comment by ekr** [comment]
Merged.
