### ISSUE TITLE
Specify semantics for duplicate oid_filters oids

### ISSUE THREAD

**Issue by kaduk** [tlswg/tls13-spec#1179]
We should say something about whether the same OID is allowed to appear multiple times in the oid_filters extension (and if it is, what the semantics are).

Extracted from #1166

**Comment by ekr** [comment]
As noted in my comments, there is a natural semantic for multiple, but it seems a bit silly. I think it would be fine to forbid them, though.

**Comment by Andrei-Popov** [comment]
I think it's OK to limit to one appearance of a given OID in the oid_filters.
(It probably does not matter much in terms of code complexity either way.)

**Comment by kaduk** [comment]
I'm inclined to limit to one appearance of a given OID in oid_filters.
