### ISSUE TITLE
CertificateType is specified but does not appear anywhere in the procol

### ISSUE THREAD

**Issue by shawnl** [tlswg/tls13-spec#1195]
AFAICT there are no current implementations of Raw Public Key (RFC 7250) for TLS 1.3. 

The spec is not clear how to specify that RawPublicKey is being used, as CertificateType (a uint8) does not appear in the protocol. Where can I fit this byte (preferrably) both for server certificate requests, and client certificates, or bit?

see  #722

**Comment by ekr** [comment]
The way this works is that you negotiate it in the client_certificate_type
and server_certificate_type extensions, and then that tells you what is in
the Certtficate.

**Comment by shawnl** [comment]
OK thanks.
