### ISSUE TITLE
7.4.2.4 does not mention which (if any) extensions are expected in the resent ClientHello.

### ISSUE THREAD

**Issue by grubba** [tlswg/tls13-spec#120]
I was just bit by my TLS 1.3 server complaining about duplicate extensions, as I had implemented the client side by just resending the original ClientHello followed by the amended ClientKeyShare.

I see a couple of possible approaches (of which the second is what I'll implement for now):

  * The second ClientHello MUST resend the same extensions with the same values as the original ClientHello.
    What about the early data extension?

  * The second ClientHello MUST NOT contain any extensions.
    Note that this would affect the security of issue #104 if the session hash is restarted.

  * The latter of course leads to the question of why resending the ClientHello at all, as all required new information will be in the ClientKeyShare.

Allowing adding of new extensions in the second ClientHello would only lead to increased complexity.

**Comment by ekr** [comment]
The specification should now be clear on this:


      When a client first connects to a server, it is required to send
      the ClientHello as its first message.  The client will also send a
      ClientHello when the server has responded to its ClientHello with
      a ServerHello that selects cryptographic parameters that don't
      match the client's ClientKeyShare.  In that case, the client MUST
      send the same ClientHello (without modification) except including
      a new ClientKeyShare.  [[OPEN ISSUE: New random values?  See:
      https://github.com/tlswg/tls13-spec/issues/185]] If a server
      receives a ClientHello at any other time, it MUST send a fatal
      "unexpected_message" alert and close the connection.
