### ISSUE TITLE
Diffie-Hellman updates.

### ISSUE THREAD

**Issue by grubba** [tlswg/tls13-spec#121]
This applies to TLS 1.3 draft 4.

The ffdhe groups in Section 7.3.2.5.2 aren't up-to-date with draft-ietf-tls-negotiated-ff-dhe-04:

   * ffdhe2432(256) has been replaced with ffdhe2048(256).

   * ffdhe6144(259) is no more.

   * ffdhe8192(260) has been renumbered to ffdhe8192(259).

The note in Section 8.1.3 has text that refers to the old TLS 1.2 and earlier key exchange method, where the server could select any DH-parameters it liked.

NamedGroup and NamedGroupList should be added to somewhere in appendix A.

**Comment by ekr** [comment]
Thanks. WRT to the appendix, I am going to let it get out of date for a draft or two and then do a mass update.

**Comment by ekr** [comment]
I am now auto-generating the appendix, so it will hopefully get less out of sync

**Comment by ekr** [comment]
Grubba, PTAL at the Pull Request above.

**Comment by grubba** [comment]
The latest FFDHE-draft (06) has reintroduced FFDHE-6144, and replaced FFDHE-2048 with FFDHE-2432, so this issue should probably be reopened.
