### ISSUE TITLE
Unsolicited extensions

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#1221]
Per @kaduk:
Apparently Johnathan Hoyland thinks that the current text allows for unsolicited non-request-response extensions unless specifically forbidden (e.g., for HRR), but Ekr and I think they are forbidden. Perhaps this should be clarified.

**Comment by ekr** [comment]
This text seems pretty clear:
```Implementations MUST NOT send extension responses
if the remote endpoint did not send the corresponding extension requests,
with the exception of the "cookie" extension in the HelloRetryRequest.
Upon receiving such an extension, an endpoint MUST abort the handshake with an
"unsupported_extension" alert.
```

Trying and failing to recall the argument for why it's not.

**Comment by kaduk** [comment]
IIRC (noting that I'm not sure I ever fully understood it) the argument here is that for a one-way extension that has no response, there is no "corresponding extension request" and so the prohibition here does not apply.

**Comment by ekr** [comment]
I see. I don't think that's correct. @jhoyla?

**Comment by ekr** [comment]
I.e., we just don't allow those in the response messages, and if you want one, you need an empty extension in the request to allow it.

**Comment by richsalz** [comment]
> and if you want one, you need an empty extension in the request to allow it.

i agree.  I thought we had at least one of those (certstatus?) but I can't recall details without looking at the RFC.  I also think the 'bitmask" doc from Yoav was intended to help address this kind of thing.

**Comment by jhoyla** [comment]
The text doesn't explicitly disallow extensions that don't follow a request / response pattern, so I don't think it's clear why someone couldn't define an extension that _only_ appears in the Encrypted Extensions say. The cookie extension, IIUC is a request / response style extension, so the exception text makes sense. It doesn't let you draw conclusions about strictly signalling extensions, for example. 
Anything that's not explicitly disallowed is, to my mind, valid. It doesn't make it a good idea, or likely to be adopted, but it's not prima facie invalid.

**Comment by ekr** [comment]
OK. I see how you get that out of the text, but I also don't think it is what was intended. Rather, indications are just requests without responses and so are subject to the same rules.

**Comment by jhoyla** [comment]
The latter, the text isn't clear. Not obvious to me why the restriction is necessary though. The client can just ignore extensions it doesn't understand, no?

**Comment by ekr** [comment]
It could, but that's just not how things are specified..
