### ISSUE TITLE
Timing of sending NST from the server

### ISSUE THREAD

**Issue by ueno** [tlswg/tls13-spec#1226]
I came across this argument: while 4.6.1 currently says:

> At any time after the server has received the client Finished message, it MAY send a NewSessionTicket message.

it is possible that the server already has sufficient information to construct a session ticket, when it sends the server Finished message, and thus it could send NST along with the first Application Data without waiting for the client Finished message.

I am wondering if this behavior has any security implication, or the above statement could be relaxed to:

> At any time after the server has sent the server Finished message, it MAY send a NewSessionTicket message.

?

**Comment by martinthomson** [comment]
Good question.  We know that - absent extensions - some servers are able to predict the client Finished and therefore construct the necessary information needed to construct a ticket.  Servers that don't use state offload can even send tickets prior to receiving the client Finished even when they require client authentication.  In both cases, this uses 0.5-RTT data for sending the ticket and as 0.5-RTT is often under-utilized that can be a fairly large performance gain.  I'd support the proposed change.

**Comment by ekr** [comment]
I think this *precise* change is a little problematic because it leaves the implementor confused about whether this is possible.

Combined with a description of the situation (an expanded version of what @martinthomson has here) I agree this would be valuable.

**Comment by ueno** [comment]
Sorry, I didn't realize that it is already covered by the Notes in the same section: "Note: Although the resumption master secret depends on the client's second flight, a server which does not request client authentication MAY compute the remainder of the transcript independently and then send a NewSessionTicket immediately upon sending its Finished rather than waiting for the client Finished." I wonder if it is still worthwhile to mention the stateful case as pointed by @martinthomson.
