### ISSUE TITLE
Is resumption allowed before initial connection is closed?

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls13-spec#1243]
Resumption before the initial connection is closed does not seem to be forbidden but RFC 8446 does not really give any answers. Oxford dictionary defines resumption as "the action of beginning something again after a pause or interruption." but I think "resumption" should just be seen as a slightly misleading name for the mechanism.

RFC 8446 makes it clear that a connection can result in several tickets and that these tickets can be used in parallel with each other. My assumption would be that the tickets can also be used in parallel with the initial connection. If that is the case it would be good to state this. If not, it would be good to state that as well.

The question came up in RFC6083bis where the suggestion is to  set up parallel connections.

I made a PR with the assumption that it’s allowed. I don’t see any reasons to forbid it, but I might miss something.

**Comment by ekr** [comment]
I concur that resumption should be permitted once the initial connection is established.

I would prefer not to change the name, just because it's historically confusing not to.
