### ISSUE TITLE
Clarifications on traffic key use

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls13-spec#1248]
I cannot find any specification in RFC8446 of which key is used to encrypt an alert or heartbeat sent before Finished (I assume it is the application_traffic_secret). It is definitly possible that this information is somewhere in the document and that I just do not find it.

The document seems to treat "record type" and "content type" as synonyms. Are both terms needed?

I would suggest updating table in section 7.3 to make it complete. Record type "Application Data" should probably be everything that is not a Handshake. It would be good to say something about post-handshake messages in section 7.3. Post-handshake messages have record type/content type Handshake but does not follow what the table in 7.3 says.

**Comment by tomato42** [comment]
The key is not specified as some errors can make it impossible for the peer to send an alert under specific key, so the used key is implicit—the currently used one, whichever it happens to be, including plaintext.

**Comment by emanjon** [comment]
True, thank for reminding me. That is quite simple.

Given that, I think the table in Section 7.3 is confusing and and not even correct.

- It claims to give the secret for each record type, but only lists 2. "0-RTT Application" is not a record type.....
- It gives the idea that the secret follows from the record type, which is not correct.
- It claims that record type Handshake is protected with [sender]_handshake_traffic_secret, but record type handshake is protected with all three secrets depending on the state.

I think it would probably be better to remove the table in 7.3 than to keep the current version. Even better would be to replace 7.3 with a more correct description.

```
   [sender] denotes the sending side.  The value of Secret for each
   record type is shown in the table below.

       +-------------------+---------------------------------------+
       | Record Type       | Secret                                |
       +-------------------+---------------------------------------+
       | 0-RTT Application | client_early_traffic_secret           |
       |                   |                                       |
       | Handshake         | [sender]_handshake_traffic_secret     |
       |                   |                                       |
       | Application Data  | [sender]_application_traffic_secret_N |
       +-------------------+---------------------------------------+

                     Table 1: Secrets for Traffic Keys
```
