### ISSUE TITLE
Data transfer limitation per connection

### ISSUE THREAD

**Issue by okoeroo** [tlswg/tls13-spec#125]
The counter has a size of (2^64-1).The records are max (2^14 + 2048). 
So, my bold calculation would come to (2^64-1) / (2^14 + 2048) / 2^40 = 910.22 TiB of data.

In Big Data, video streaming and other mass data cases 910TB data can be a limitation.

I would like to propose the counter to go to 2^128-1, which would result in a connection that can reach (2^128-1) / (2^14 + 2048) / 2^80 = 1.52 * 10^10 YiB.

If byte preservation is an issue, I'm willing to accept 2^96-1 as the counter max, resulting in (2^96-1) / (2^14 + 2048) / 2^80 = 3.55 YiB as maximum connection.

**Comment by uforia** [comment]
On a 40Gbit line this will take less time than one might expect: http://www.wolframalpha.com/input/?i=910.22TiB+at+40Gbit%2Fs (let's say 2.5-3 days with overhead).

**Comment by grubba** [comment]
Why do you divide by (2^14 + 2048)? Shouldn't it be a multiplication with the minimum record size?

**Comment by ekr** [comment]
I don't see much support for this. Please take it to the list if you want to pursue it.

**Comment by ekr** [comment]
Consensus at interim:
No protocol action needed. Add calculations to security considerations.

**Comment by richsalz** [comment]
Also, consensus is that the math above is wrong.

**Comment by ekr** [comment]
@wbl would you be willing to contribute a PR with a paragraph or two of guidance on the limits for AES-GCM and ChaCha20

**Comment by wbl** [comment]
Yes. What happened to the Key Update message? I can't find it in the text, and that would be a logical place to mention the limitations as well as in the security considerations section.

**Comment by ekr** [comment]
https://github.com/tlswg/tls13-spec/pull/354

If you want to just send a PR against that branch that would be fine. Or really, whatever form you want and I can manually merge.
