### ISSUE TITLE
Multiple post-handshake authentications, identities, and tickets.

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls13-spec#1250]
RFC 8446 makes it clear that the client can recieve any number of CertificateRequests but RFC 8446 does not say anyhting about identities when the client authenticates several times. RFC 8446 does not seem to forbid the server to accept authentication with completely different identities each time. Is this a feature or a bug?

I assume you could have a client first authenticate as a user and then as root, but this would mean that a connection is associated with several identities and not only "the identity" that RFC8446 and [Kraw16] talk about. Several identities also makes it hard to determine which identity a specific ticket belong to. RFC8446 states that data before authentication was sent/received by the identity that later authenticated.

- Would it make sense to add something like the sentence below to 4.6.2 (leaving the definition of identity up to the application).

"If the server at some point in the connection has considered the client authenticated with one identity, it MUST not consider the client authenticated with another identity."

- If the idea is to support authentication with several identities, I think other parts of RFC8446 should be updated. The document should then not talk about “the identity” and consideration on which identity a certain ticket belongs to should be added. Maybe tickets would have to be made invalid.

**Comment by tomato42** [comment]
IIRC the consensus was that it was up to the protocol using TLS 1.3 to define how it should be handled and if multiple client identities are allowed

**Comment by kaduk** [comment]
Given that we are admitting the possibility of the server authenticating as multiple identities, I would be reluctant to rule it out for the client.  I don't have as clear a recollection as Hubert does, but leaving it to the consuming application seems likely to be the best we can really do, other than providing warnings about the semantics of multiple identities being hard to nail down.

**Comment by ekr** [comment]
That is my thought as well. I believe we should close this as wontfix.

**Comment by ekr** [comment]
Discussed in Vienna. Closed.
