### ISSUE TITLE
Should we recommend rekey with ECHDE after a certain amount

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#1253]
@emanjon proposed 100GB.

I tend to think no guidance is needed but I filed this issued to keep track.

**Comment by martinthomson** [comment]
That seems arbitrary.  And large enough that it would be very rare.  And unlikely to be followed as you lose state by creating a new connection.  I'd say that no guidance is best.

**Comment by ekr** [comment]
Closing per discussion in Vienna.
