### ISSUE TITLE
token_binding does not have TLS 1.3 extension markers in IANA

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#1278]
See:
https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#tls-extensiontype-values-1

It probably should, though. @martinthomson @davidben, thoughts?

**Comment by davidben** [comment]
Ah probably. I guess CH, EE?

**Comment by nharper** [comment]
If we want to list something other than "-" in the registry, someone would need to request the review to go through the Specification Required process. (https://datatracker.ietf.org/doc/html/draft-ietf-tokbind-tls13-03 is such a specification.)

**Comment by ekr** [comment]
OK, I guess we can just close this.
