### ISSUE TITLE
Server Tracking Prevention is also needed

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls13-spec#1289]
The document has a section on Client Tracking Prevention which is what is relevant for the Web. For IoT the TLS server is often a device. That device might be something that a person takes with them.

Motivation for changes is given by the charter.

```
Security and privacy goals will place emphasis on the following:

- Identify and mitigate other (long-term) user tracking or fingerprinting
vectors enabled by TLS deployments and implementations.
```

**Comment by emanjon** [comment]
This seems to be an easy fix. Just chaning the heading from "client tracking prevention" to "client and server tracking prevention" seems to do the job

**Comment by ekr** [comment]
Fixed
