### ISSUE TITLE
Key update a MUST?

### ISSUE THREAD

**Issue by BenSmyth** [tlswg/tls13-spec#1299]
Limits on Key Usage (Section 5.5):

> There are cryptographic limits on the amount of plaintext which can be safely encrypted under a given set of keys...Implementations SHOULD do a key update as described in Section 4.6.3 prior to reaching these limits.  

Since key updates are necessary for security, I think MUST (rather than SHOULD) is appropriate. 

(And similarly in the sentence that follows: "Note that it is not possible to perform a KeyUpdate for early data and therefore implementations SHOULD not exceed the limits when sending early data.")

**Comment by BenSmyth** [comment]
@tomato42 That seems compatible with MUST: 

> There _are_ cryptographic limits...Implementations [MUST] do a key update...prior to reaching these limits.

Section 5.5 also notes:

> For ChaCha20/Poly1305, the record sequence number would wrap before the safety limit is reached.

It follows that implementations might not do a key update.

**Comment by ekr** [comment]
I don't necessarily object to a MUST but I think as with the limit on KeyUpdate it would need to be paired with a MUST NOT enforce on the receiver. As I understand it, these bounds aren't necessarily tight, so we might have some results that allowed fewer rekeys in the future.
