### ISSUE TITLE
Erratum: logic inversion on ENCRYPTED-KEY-DATA padding check

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#13]
http://www.rfc-editor.org/errata_search.php?rfc=5246&eid=2643

Section E.3 says:

> When a TLS-capable server negotiates SSL 2.0 it SHOULD, after
decrypting the ENCRYPTED-KEY-DATA field, check that these 8 padding
bytes are 0x03.  If they are not, the server SHOULD generate a random
value for SECRET-KEY-DATA, and continue the handshake (which will
eventually fail since the keys will not match).

It should say:

> When a TLS-capable server negotiates SSL 2.0 it SHOULD, after
decrypting the ENCRYPTED-KEY-DATA field, check that these 8 padding
bytes are not all 0x03.  If they are, the server SHOULD generate a random
value for SECRET-KEY-DATA, and continue the handshake (which will
eventually fail since the keys will not match).

The condition is the wrong way around. When the bytes *are* all 0x03, that means the client supports TLS, so there must have been a version rollback attack in order for SSL 2.0 to be negotiated.

**Comment by davegarrett** [comment]
This section was dropped as SSL2 is now prohibited entirely, so this issue is no longer applicable and can be closed.
