### ISSUE TITLE
Requirements or guidance to not use external psk identities like john.mattsson@ericsson.com

### ISSUE THREAD

**Issue by emanjon** [tlswg/tls13-spec#1308]
How the external PSK identity is chosen matters a lot.

- An identifiers such as john.mattsson@ericsson.com can be used to trivially identify someone.
- A random identifier such as dxv1hwqvf6 can typically only be used for tracking/fingerprinting. But if the person behind one of the connections is identified than the attacker knows the identity behind all the connections.
- A random identifier such as dxv1hwqvf6 that is only used once cannot be used for tracking/fingerprinting.

As far as I can see the TLS specification does not say anything regarding psk identities like john.mattsson@ericsson.com. Modern EAP methods such as EAP-TLS 1.3 and EAP-AKA FS requires a "privacy-friendly" identifier. TLS 1.3 should say something about identifiers like john.mattsson@ericsson.com that can be used to identity someone. SHOULD NOT or MUST NOT seems appropriate.

**Comment by ekr** [comment]
@chris-wood I'm trying to recall what we decided here.

**Comment by tomato42** [comment]
-1 for "MUST NOT", while useful, it brings unneeded and unnecessary complexity for point to point connections

**Comment by chris-wood** [comment]
I think the WGLC concluded without concrete suggestions for this issue, which I interpret to mean that no changes are needed. I think we can therefore close this.

**Comment by emanjon** [comment]
In the mobile industry permanent identifiers is seen like something that should be phased out and forbidden. TLS 1.3 not taking any normative actions against permanent identifiers that can trivially be used by passive attackers to uniquely identify and track both clients and servers would be very disappointing and bad for privacy not just in TLS 1.3 but for the ICT industry in general. Just because some companies are using permanent identifiers does not mean it is acceptable.

**Comment by ekr** [comment]
How about this text? https://github.com/tlswg/tls13-spec/pull/1325

**Comment by martinthomson** [comment]
> In the mobile industry permanent identifiers is seen like something that should be phased out and forbidden. 

Like E.164?  :)  I do agree with the sentiment though; it's a good goal to work towards.
