### ISSUE TITLE
illegal_parameter vs protocol_version

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#1339]
Sec 4.1.2. say:

> A server which receives a legacy_version value not equal to 0x0303 MUST abort the handshake with an "illegal_parameter" alert.

Why isn't "protocol_version" used?

**Comment by davidben** [comment]
`protocol_version` is defined as:

> protocol_version:  The protocol version the peer has attempted to
>      negotiate is recognized but not supported (see [Appendix D](https://datatracker.ietf.org/doc/html/rfc8446#appendix-D)).

The wrong value in `legacy_version` isn't negotiating the wrong version. It's just a syntax error.

**Comment by kazu-yamamoto** [comment]
But E.2. says:

> If the "supported_versions" extension is absent and the server only supports versions greater than ClientHello.legacy_version, the server MUST abort the handshake with a "protocol_version" alert.

In this case, "protocol_version" is used.
For simplicity, I would like to recommend "protocol_version" for the case above, too.

**Comment by ekr** [comment]
Absent more support, I propose to leave this as-is. At worst it's a judgement call and not an interop problem, and so I think out of scope for the 8446-bis effort. Target date: 2/29.
