### ISSUE TITLE
Clarify interaction of session resumption and version negotiation

### ISSUE THREAD

**Issue by davidben** [tlswg/tls13-spec#136]
(Apologies if this is the wrong medium. I wasn't sure if issues here or emails to the list were preferred since these aren't huge changes.)

How version negotiation interacts with session resumption isn't said explicitly. Two little things that probably should be fixed:

On the server, clarify that you MUST NOT resume a session at a version other than the original one. Instead, ignore the offered session and do a full handshake. This is easy to justify: every client (I tested NSS, OpenSSL, SecureTransport, and SChannel) will fail the handshake if the server tries to mismatch. It's also weird. (Say a future TLS version changed the master secret size...) Still, OpenSSL happily did so until [recently](https://git.openssl.org/gitweb/?p=openssl.git;a=commit;h=9e189b9dc10786c755919e6792e923c584c918a1).

On the client, RFC 5246, E.1 has this little paragraph that seems to have carried over into 1.3.

> Whenever a client already knows the highest protocol version known to
> a server (for example, when resuming a session), it SHOULD initiate
> the connection in that native protocol.

This is terrible advice. The parenthetical bit is wrong, but I would push for dropping it completely. The server may have changed, there may be multiple differently-configured servers behind that host, the session may have been established under fallback conditions, etc.

OpenSSL takes it to an [extreme](https://crbug.com/403378) and [breaks](https://crbug.com/417134) [horribly](https://twitter.com/pzb/status/531677249909821440). (I ended up completely rewriting this bit for BoringSSL.) NSS [cites that text](https://chromium.googlesource.com/chromium/src/+/master/net/third_party/nss/ssl/ssl3con.c#5096) in something less catastrophic but still has the second "sticky fallback" failure mode.

**Comment by briansmith** [comment]
I support removing that text. See also earlier discussion:
http://www.ietf.org/mail-archive/web/tls/current/msg13732.html
http://www.ietf.org/mail-archive/web/tls/current/msg13869.html

Note that when a client does not consistently use the same ClientHello.client_version, it should probably avoid attempting to resume a session X if it used a different ClientHello.client_version for the connection that created session X than it is attempting to use in the current ClientHello. The consequence of this is that these clients should store ClientHello.client_version in the session cache entry. However, it is better for them to always consistently set ClientHello.client_version to TLS 1.2.

**Comment by davidben** [comment]
Having generic text to take care when mixing session caches between contexts with different parameters is probably worthwhile yeah. Sharing a session cache between a pile of sockets that, say, turn off AEADs and a pile that don't is also iffy. The client_version seems rather specific requirement to put in, and requiring TLS impls to store the entire ClientHello in the session cache seems a bit much.

I actually don't see what doing just the client_version buys for the extra state, at least in contexts where a browser does it. Are you thinking to do that to account for the NSS client_version clamping behavior, the old OpenSSL server one when combined with fallbacks, or something else?

If the NSS side, that would mean NSS never resumes sessions on any but the highest version. It should just remove that logic; neither SChannel nor Secure Transport did it when I tested. Chrome + BoringSSL doesn't either and we haven't had problems. (It's hit stable on Mac and beta on Windows.)

If the old OpenSSL server behavior (and without FALLBACK_SCSV) and you should have negotiated a stronger TLS-1.2-only cipher, an attacker could just trigger the fallback again anyway, so we're not gaining much. That seems best fixed on the server (and has been now). In fact, if the server wants to be extra fancy, it could simulate picking a new cipher and only accept the session if that matched. But probably expiring old sessions when changing server config works just as well there. (That may also be worth some text: servers should take care when considering old sessions across a server config change.)

**Comment by briansmith** [comment]
I mean this (acting as the client):

1. Decide what number (e.g. TLS 1.2) you are going to put in ClientHello.client_version and what cipher suites you are going to send in the ClientHello.

2. Search the session cache for a matching entry, where the session was established on a connection where ClientHello.client_version matches the ClientHello.client_version you picked in the previous step, and where the cipher suite for the cached session matches a cipher suite in the set of cipher suites you've enabled for the current ClientHello. Note that we're matching ClientHello.client_version to ClientHello.client_version, NOT to the version that was negotiated (ServerHello.server_version).

3. If the server attempts to resume the session with a different server_version or a different cipher suite, then something's gone very wrong; bail!

The idea here is to avoid cases where the server may do strange things like use a different ServerHello.server_version or a different cipher suite than what was originally negotiated. As you mentioned, the logic I described isn't enough to prevent all silliness, but I think it would avoid most cases.

**Comment by ekr** [comment]
We removed resumption entirely as of draft-07 so I think this is OBE.

**Comment by martinthomson** [comment]
It's renegotiation that was removed.  This might still be relevant.

**Comment by ekr** [comment]
Well, we removed explicit resumption as well, and at least technically you could do PSK-resumption with different cipher suites and/or versions.
