### ISSUE TITLE
Fix which master secret is used for exporters

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#138]
The current text claims that the HMS should be used for Exporters. That
doesn't make sense. The MS should be used for Exporters.

**Comment by martinthomson** [comment]
Given the potential for us to update the MS with the update mechanism, I'm going to suggest that a new exporter MS be generated from the HMS.

**Comment by ekr** [comment]
I'm going to fix this thinko now for draft submission. and leave your point pending post-interim revisions of the key schedule
