### ISSUE TITLE
Remove TLSCiphertext.opaque_type & TLSCiphertext.record_version

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#144]
TLSCiphertext.record_version provides no useful information, encourages implementations to check it unnecessarily, and wastes two bytes per record. It should be removed entirely.

This is effectively dependent on PR #51 or similar changes.

Filing this as a specific issue rather than just bringing it up in backwards compatibility discussion.

Edited to add:
Note that this value is called TLSCiphertext.version in TLS 1.2 and TLSCiphertext.record_version as of TLS 1.3 draft 06. The TLSPlaintext equivalent of this version field cannot be removed as it is required for backwards compatibility, however it's only used with ClientHello at this point.

**Comment by ekr** [comment]
Defer pending measurements. Note that this fate shares with removing the cleartext content type

**Comment by davegarrett** [comment]
sgtm

Amending issue title.

**Comment by ekr** [comment]
Mozilla is working on measurements.
