### ISSUE TITLE
Specifying MUST NOT behavior

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#156]
There are a couple of places in the spec where it says client/server MUST not do x but doesn't specify what happens if they do.  Should we specify that behavior?

Some examples:
s7.3.2:  Clients MUST NOT offer multiple ClientKeyShareOffers for the same parameters.

s7.3.2.5: There MUST NOT be more than one extension of the same type.

s7.3.2.5.1:  signature  ... It MUST NOT appear in this extension.
  and Servers MUST NOT send this extension.

s7.3.2.5.3:  If the EarlyData extension is used, then clients MUST NOT send any messages other than the ClientHello in their initial flight.
and Servers MUST NOT send the EarlyData extension.

sA.4: TLS_NULL_WITH_NULL_NULL is specified and is the initial state of a TLS connection during the first handshake on that channel, but MUST NOT be negotiated, as it provides no more protection than an unsecured connection.

**Comment by grubba** [comment]
Sounds like a good idea. I assume that the proper response is for the peer to send a fatal alert, but specifying exactly what alert is probably a good idea.

**Comment by davegarrett** [comment]
I started some work on this here:
https://github.com/davegarrett/tls13-spec/compare/seanfixesredux...davegarrett:morealerts
PRs accepted to the "morealerts" branch for more.

**Comment by davegarrett** [comment]
This is addressed in PR #201.
