### ISSUE TITLE
Erratum: padding

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#16]
We might just close this one out based on #7.

See http://www.rfc-editor.org/errata_search.php?rfc=5246&eid=2390

Section 6.2.3.3 should have marked text on padding removed:

>   The additional authenticated data, which we denote as
   additional_data, is defined as follows:

>      additional_data = seq_num + TLSCompressed.type +
                        TLSCompressed.version + TLSCompressed.length;

>   where "+" denotes concatenation.

>   The aead_output consists of the ciphertext output by the AEAD
   encryption operation.  The length will generally be larger than
   TLSCompressed.length, but by an amount that varies with the AEAD
   cipher.  ~~Since the ciphers might incorporate padding, the amount of
   overhead could vary with different TLSCompressed.length values.~~  Each
   AEAD cipher MUST NOT produce an expansion of greater than 1024 bytes.
   Symbolically,

 I suggest leaving the sentence about padding out. The value for TLSCompressed.length is required by additional_data for both encryption and decryption. Therefore, it must be possible to determine the TLSCompressed.length from the ciphertext before decryption.

In practice this is done by subtracting the integrity check value length from the ciphertext length, where the integrity check value length is defined by each AEAD cipher separately. If the cipher incorporates variable padding, it is impossible to calculate the TLSCompressed.length without an explicit value sent for each ciphertext separately. Therefore to avoid confusion, it would be better not to mention anything about padding at all.

(issue discussed on tls@ietf.org and with Eric Rescorla, result of both discussions was that padding in AEAD ciphers doesn't seem to be possible with the current specification)

**Comment by ekr** [comment]
We removed length form the additional data, so I believe this is no longer relevant.
