### ISSUE TITLE
Restore empty compression field in ServerHello?

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#161]
Brian Smith writes:

> (note that ServerHello is already changed by dropping compression_method)

That seems unnecessary to me. compression_method could/should just be
fixed to be "null", avoiding unnecessary compatibility risk.

**Comment by davegarrett** [comment]
There's only a compatibility risk if there's the possibility of a TLS 1.3 ServerHello being sent do an older client that cannot understand it. If we switched to a list based negotiation, this would be impossible.

(you're quoting me, not Brian, btw)

**Comment by ekr** [comment]
Closing for now.
