### ISSUE TITLE
Sign Ephemeral Parameters *and* the context

### ISSUE THREAD

**Issue by tomrittervg** [tlswg/tls13-spec#181]
See: LogJam, [Mavrogiannopoulos, et al](http://dl.acm.org/citation.cfm?id=2382206), and [Schneier/Wagner](https://www.schneier.com/paper-ssl-revised.pdf). (And perhaps this [message/thread](http://www.ietf.org/mail-archive/web/tls/current/msg16361.html))

The Ephemeral Parameters should include some context in the signature. Some options:
 - Algorithm (this wouldn't have prevented LogJam or Mavrogiannopoulos)
 - Ciphersuite (this wouldn't prevent Mavrogiannopoulos)
 - Transcript up to that point
 - Some "let's try to be clever" choice of Algorithm, Ciphersuite, and other context

**Comment by ekr** [comment]
We presently sign the entire transcript.
