### ISSUE TITLE
Prune EC curves and remove md5

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#186]

**Comment by davegarrett** [comment]
Here's a PR for this: #188 

Question: Are we dropping all curves <224 bits or <255 bits?
(was consensus ever called on this specific number?)

**Comment by seanturner** [comment]
There was not a specific WG consensus call on this point.  I hope we don't need one and that we should keep the curves in that are used and trim the ones that aren't.

**Comment by davegarrett** [comment]
Good. In that case, I'll slash everything other than secp256r1 (prime256v1 / NIST P-256), secp384r1 (NIST P-384), secp521r1 (NIST P-521), and sect571r1 (NIST B-571). (plus, of course, new CFRG curves yet to be added) PR updated.

https://tools.ietf.org/html/rfc4492#appendix-A
https://securitypitfalls.wordpress.com/2015/05/23/april-2015-scan-results/

**Comment by davegarrett** [comment]
Based on the fact that apparently precisely zero servers actually use SHA-224 for signatures, can we drop that too while we're at it? (not an exaggeration; the scan cited in the last comment shows none)

**Comment by seanturner** [comment]
I would drop it.

spt

**Comment by davegarrett** [comment]
OK. PR updated.

**Comment by davegarrett** [comment]
@ekr: This can be closed now that PR #188 has been merged.
