### ISSUE TITLE
Omit ClientKeyShare if it's empty

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#190]
Now that ClientKeyShare is looking like an extension, should we omit it if it's empty.

**Comment by ekr** [comment]
Consensus: omit if empty

**Comment by martinthomson** [comment]
Of course, if ServerKeyShare is the same extension, then it can't be empty from the client.

**Comment by davegarrett** [comment]
It could probably be omitted in a system with one generalized key sharing extension, however I think it's simpler to just spend the 6 bytes for an empty offer than to have an extension with special permission to be added to a retried ClientHello. I don't like special cases if I can avoid them. I can't say for sure until I'm done with the patch and ready to submit a PR, though.

**Comment by martinthomson** [comment]
Actually, thinking on this more, you can safely omit it.  It prevents the server from generating shares, but that isn't actually bad.  It prevents the client from being tricked by a falsified `HelloRetryRequest`.  In any case, you can't use the server's share until after the `HelloRetryRequest` and subsequent `ClientHello` anyway.

**Comment by ekr** [comment]
Omitted.
