### ISSUE TITLE
Having record_version in the AD is redundant.

### ISSUE THREAD

**Issue by grubba** [tlswg/tls13-spec#193]
(Draft 6)
Sections 6.2.1 and 6.2.2 hard code record_version to { 3, 1 }. Having this constant value in the authenticated data (section 6.2.2) doesn't have any function. I suggest either replacing it with the negotiated protocol version (also a bit redundant, but better as it could change with TLS 1.4), or removing it.

**Comment by davegarrett** [comment]
This is a duplicate of issue #144.
