### ISSUE TITLE
When does the session ticket lifetime start?

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#204]
https://tlswg.github.io/tls13-spec/#new-session-ticket-message
> ticket_lifetime_hint
>    Indicates the lifetime in seconds as a 32-bit unsigned integer in
>    network byte order. A value of zero is reserved to indicate that
>    the lifetime of the ticket is unspecified.

Lifetime counting from when? There could be a big difference between the lifetime since having the ticket issued (or connection start) and the lifetime of the ticket being valid after the connection is closed. So, should this value be counting from ticket issue or connection close? Either way, it should be specified.

**Comment by ekr** [comment]
It should be from ticket issue, which is consistent with the existing draft (where it's from the time of the handshake which is at ticket issue).
