### ISSUE TITLE
Make EncryptedExtensions mandatory

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#213]
In #211, @davegarrett suggests that the added EncryptedExtensions message from the client should be optional.  I'd rather make it mandatory and simply carry the extra bits if it happens to be empty.  The fewer optional parts the better.

**Comment by davegarrett** [comment]
The server-side one is optional, but the client-side one in that PR isn't. Consistency, either way, is probably a good idea.

That said, I agree with your assessment. All usually needed handshake messages should probably be mandatory, with empty fields if not needed. This seems like a good idea to reduce risk potential issues from unneeded complexity.

I see you also filed issue #212, which is another straightforward way to reduce complexity here. Also, turning ServerKeyShare into an extension to stick directly into ServerHello, as has been done already on the client-side, could simplify things a bit as well.

**Comment by ekr** [comment]
Yes, this is just pilot error. They should all be mandatory.

**Comment by ekr** [comment]
This should be done now.
