### ISSUE TITLE
Explicit API recommandation for a TLS stack

### ISSUE THREAD

**Issue by beurdouche** [tlswg/tls13-spec#216]
At some point in the future we should try to include a protocol API for implementations to follow.
I do understand that current libraries implementing their own API will not follow that soon (or ever) but new implementations could benefit from that ...

**Comment by ekr** [comment]
@beurdouche this seems like a great companion document

**Comment by richsalz** [comment]
Also, perhaps look at libtls from openbsd: http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/tls_accept_fds.3?query=tls_init&sec=3

**Comment by dwmw2** [comment]
Please ensure that any such API recommendation covers the use of *(esp. client)* certificates. In particular, there should be an API which applications can use to simply ask the library to use a certificate/key specified by the user, from a file or ([RFC7512](http://tools.ietf.org/html/rfc7512)) PKCS#11 URI.

Applications currently have to jump through a *lot* of hoops even to have comprehensive support for files — often having to determine for *themselves* if a file is PEM- or DER-encoded, if it's PKCS#1, PKCS#8, PKCS#12 or something more esoteric, and then invoke the library API [differently](http://www.advogato.org/person/dwmw2/diary/205.html) for each type of file.

There should be a simple function that the application can call, with the filename/URI string(s) provided by the user, and expect the library to do the right thing.

**Comment by ekr** [comment]
I don't think this belongs in the main spec, so I'm parking it.

**Comment by dwmw2** [comment]
FWIW in case this does get picked up again here or elsewhere, here's a document which attempts to address the use of certificates from such an application: http://david.woodhou.se/draft-woodhouse-cert-best-practice.html
