### ISSUE TITLE
Remove DSA support

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#222]
It has been suggested we should remove DSA. Tracking issue

**Comment by beurdouche** [comment]
+1

**Comment by ekr** [comment]
@seanturner do we have consensus on this or can you call for it on-list?

**Comment by seanturner** [comment]
we should do a call, but I�ll phrase it as in is there anybody who wants to speak in favor of keeping it.

spt

**Comment by davegarrett** [comment]
@seanturner: Also, please clarify if it's to just be dropped from the document, but technically still permitted, or dropped from the spec and no longer considered acceptable with TLS 1.3+.

**Comment by ekr** [comment]
I would prefer we either allow it or not, but not have it exist in some intermediate status.

**Comment by davegarrett** [comment]
I'm not a fan of keeping it technically permitted either, but I think there was mention of this on-list at some point. I don't remember this being explicitly decided.

**Comment by ekr** [comment]
This was done.
