### ISSUE TITLE
Indicate deprecated extensions

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#225]
Provide a list of the deprecated extensions.

**Comment by beurdouche** [comment]
Would you prefer having all deprecated stuff into the main TLS 1.3 RFC or maybe having a separate document explicitly containing all deprecated stuff like extensions, ciphers, signature algs … and explaining why ?

**Comment by martinthomson** [comment]
I think that the cipher suites are covered already. Noting that we don't support point compression negotiation (for instance) would be good.
