### ISSUE TITLE
Require that ServerConfiguration not be acceptable till handshake finished

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#229]
Hubert Karlo writes:
> > > Also, the record protection used for early handshake messages should be
> > > indicated.
> >
> > Can you expand on that?
>
> How does the client know what record protection algorithms are valid
> for 0RTT transmission for that server?

And how does the client know that the algorithms came from the server. We
should have a "client MUST wait for the full handshake to finish before
recording this information" or we will have a very nice cipher downgrade. Just
having it signed is likely not a good idea, as they may depend on ciphersuites
advertised by client.

**Comment by martinthomson** [comment]
Since the ServerConfiguration and the suites are covered by the signature the server provides, isn't it safe to use the configuration add soon as you have verified the server identity?

**Comment by martinthomson** [comment]
n.b., I have no problem with mandating that clients wait for finished, because it is immediately after the signature, but I wasn't the properties to be clear.
