### ISSUE TITLE
Remove unknown_psk_identity?

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#230]
This doesn't really make sense with the current PSK
 negotiation scheme where the client provides multiple PSKs in
 flight 1.

**Comment by davegarrett** [comment]
There's no reason a client couldn't send a giant pile of identities and still have them all be useless for the server in question. Likewise, the server could still have a bug and pick an unsupported PSK, in which case having a specific error would help debugging. There's also the new use-case of PSK resumption, so if a client picks a PSK for resumption that the server doesn't have around to use anymore, it could easily hit this error.

It's also a pre-existing error alert, so I don't see a point in removing it now. Might as well just leave in as it's already standardized and is technically optional anyway. (defined in RFC 4279)
