### ISSUE TITLE
consider reordering handshake protocol sections

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#237]
Currently, we have:
6. The TLS Handshaking Protocols
    6.1. Alert Protocol
        6.1.1. Closure Alerts
        6.1.2. Error Alerts
    6.2. Handshake Protocol Overview
        6.2.1. Incorrect DHE Share
        6.2.2. Zero-RTT Exchange
        6.2.3. Resumption and PSK
    6.3. Handshake Protocol
        6.3.1. Hello Messages
        6.3.2. Hello Extensions
        6.3.3. Server Key Share
        6.3.4. Encrypted Extensions
        6.3.5. Server Certificate
        6.3.6. Certificate Request
        6.3.7. Server Configuration
        6.3.8. Server Certificate Verify
        6.3.9. Server Finished
        6.3.10. Client Certificate
        6.3.11. Client Certificate Verify
        6.3.12. New Session Ticket Message

This feels like it's not completely in a consistent order, which could make it a little confusing to read through. I think we should consider reordering these sections in the order they're actually used. The list in Handshake Protocol Overview should also be in the same order. This means:
* Alert Protocol after Handshake Protocol
* order messages' sections based on send order (move Server Configuration)

So, something more like this, instead:
6. The TLS Handshaking Protocols
    6.1. Handshake Protocol Overview
        6.1.1. Incorrect DHE Share
        6.1.2. Zero-RTT Exchange
        6.1.3. Resumption and PSK
    6.2. Handshake Protocol
        6.2.1. Hello Messages
        6.2.2. Hello Extensions
        6.2.3. Server Key Share
        6.2.4. Encrypted Extensions
        6.2.5. Server Configuration (moved up)
        6.2.6. Server Certificate
        6.2.7. Certificate Request
        6.2.8. Server Certificate Verify
        6.2.9. Server Finished
        6.2.10. Client Certificate
        6.2.11. Client Certificate Verify
        6.2.12. New Session Ticket Message
    6.3. Alert Protocol (moved down)
        6.3.1. Closure Alerts
        6.3.2. Error Alerts

As @ekr is planning on rewriting quite a bit, I'm just filing this idea as an issue for consideration later on.

Another idea might be to also split 1-RTT into its own section to go right before the 0-RTT section and leave Handshake Protocol Overview as a more basic and generic explanation of what goes into the handshake. (also move Incorrect DHE Share down to after those & PSK)

**Comment by ekr** [comment]
I've done some restructuring here, so I think this is largely overtaken by events. I'll bear the rest of these ideas in mind for when I do big-time rewriting.
