### ISSUE TITLE
Eliminate TLS_NULL_NULL_WITH_NULL_NULL_NULL_NULL

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#251]
This was always a hack.  We should just remove mention of this as a "cipher suite" and just talk about certain messages being encrypted and others not.

**Comment by davegarrett** [comment]
If issue #214 is done, then I think the only cleartext messages left would be the 3 hello messages: ClientHello, ServerHello, & HelloRetryRequest. TLSPlaintext could then just be renamed to TLSHelloRecord, which would make the distinction between cleartext and encrypted records relatively easy.

**Comment by briansmith** [comment]
I agree that this psuedo-cipher-suite should be removed. It is confusing. Some implementations may work in a way where they implement some TLS_NULL_NULL_WITH_NULL_... cipher suite, but that's an implementation detail. Other implementations, particularly implementations that don't do renegotiation, likely won't work like that.

**Comment by briansmith** [comment]
I agree that this psuedo-cipher-suite should be removed. It is confusing. Some implementations may work in a way where they implement some TLS_NULL_NULL_WITH_NULL_... cipher suite, but that's an implementation detail. Other implementations, particularly implementations that don't do renegotiation, likely won't work like that.
