### ISSUE TITLE
Relax the TLS extension IANA policy?

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#252]
TLS Cipher Suite Registry: Future values with the first byte in
      the range 0-191 (decimal) inclusive are assigned via Standards
      Action [RFC2434].  Values with the first byte in the range 192-254
      (decimal) are assigned via Specification Required [RFC2434].
      Values with the first byte 255 (decimal) are reserved for Private
      Use [RFC2434].

**Comment by davegarrett** [comment]
The title here says "extension" but comment 0 says "cipher suite". You meant the latter, correct? Extension ID registry is simply "allocated via IETF Consensus [RFC2434]".

**Comment by ekr** [comment]
No, i meant extension. IETF Consensus is stronger than Specification required.

**Comment by davegarrett** [comment]
So comment 0, with the "TLS Cipher Suite Registry" policy pasted up there, is what you're suggesting modeling extensions on? e.g. Something like:
0x0000 - 0x0fff : IETF Consensus (almost all current extensions; some standards, some not)
0x1000 - 0x7fff : Specification Required
0x8000 - 0xefff : Private Use
0xf000 - 0xffff : Standards Action (renegotiation_info is in here)

Link to the current registry:
https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#tls-extensiontype-values-1
