### ISSUE TITLE
PRF negotiation

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#26]
Mike StJohns notes that the hash function used in the PRF isn't known until the ServerHello is received by a client.  This means that the client needs to either calculate and store multiple hashes of the ClientHello OR remember the contents of the ClientHello.

Alternatively, negotiation of the hash function can be removed.  SHA-256 might be good enough until we get to the next version of the protocol.

**Comment by ekr** [comment]
Closing. Please bring up on list if you want to continue
