### ISSUE TITLE
prohibit immediate plain PSK negotiation if no usable (EC)DHE key is provided, but could be, and any (EC)DHE suite is offered at a higher priority

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#277]
There's a specific risk with plain PSK (no (EC)DHE) that needs explicit handling here. Assume the following:
1) Client offers both plain PSK & any other (EC)DHE suite (e.g. (EC)DHE-PSK)
2) Server supports both as well
3) The client does not provide a (EC)DHE key share that the server can use

There is a risk that the server will:
1) Skip all (EC)DHE suites due to lack of usable key share
2) Continue checking other suites, and then negotiate plain PSK if supported

Instead, we need to explicitly make sure that this scenario triggers a HelloRetryRequest so that the client has a chance to get PFS and not accidentally be downgraded to plain PSK. (especially if plain PSK is lowest priority, as it should be)

Edited to add:
Of course, this also needs to handle the case where there is no group support overlap and plain PSK is the correct choice.

**Comment by ekr** [comment]
This doesn't seem right, because in order to do resumption, you offer plain PSK and your ordinary ECDHE (non-PSK) cipher suite and you expect the server to pick one or the other, and quite
possible that you want them to prefer PSK-only.

It might be possible to restrict to not allowing ECDHE-PSK and plain PSK together, but then you basically couldn't resume ECDHE-PSK.

**Comment by davegarrett** [comment]
If plain PSK is top priority, then it should get picked and that's that. If it's not, e.g. the client cipher list is (EC)DHE-CERT-AES, (EC)DHE-PSK, plain PSK, (in this descending priority order) and there's no usable group in the client's key share, but there is a usable PSK identity, the point I'm making is that the correct route is to request a retry to try to get a usable (EC)DHE key to do one of the first two rather than just going straight to plain PSK. In the case of resumption, the client knows what works with the server and has no reason to offer an unusable offer set. If that changes due to a config change, resumption really isn't an option anymore anyway.

The retry mechanism explicitly sets up (EC)DHE negotiation as 1RTT ideal, or 2RTT as fallback. I'm concerned that also offering plain PSK could lead to short-circuiting that and servers just ditching PFS to save a RTT (possibly accidentally).

**Comment by davegarrett** [comment]
I'll add the word "immediate" to the title to make it more clear. If the retry fails, then plain PSK is correct. It should attempt it, though.

**Comment by davegarrett** [comment]
Note that the retry "fails" just by the server checking the supported groups and seeing no overlap with itself.

**Comment by ekr** [comment]
I'm not really following the algorithm you propose. Can you write it as a bulleted list or something?

**Comment by davegarrett** [comment]
Yeah, it's sort of a narrow issue.

Plain PSK should only be negotiated in one of the two following scenarios:
1) plain PSK is top priority of mutual supported ciphers
2) it is not top, but ones earlier in the list are unusable due to known unsupported groups

We can, however, hit a third case where we have a supported group that simply did not have a key sent. This fact is what causes the hiccup.

The server needs to iterate through the mutually supported cipher list, in descending order of priority, to look for the highest priority supported cipher suite. If the suite is negotiable with the current available information, great; done. Otherwise, if it finds a suite where all three of the following are true:
1) it's (EC)DHE
2) A mutually supported group is known via the supported_groups extension
3) No mutually supported key was offered for said group in the key share extension
Then, as a consequence, it should stop right there and kick off a HelloRetryRequest to get a key and negotiate that cipher suite. It should NOT continue iterating down through the list and then instead negotiate a lower priority suite that it does currently have enough information to use.

From another perspective, HelloRetryRequest makes the operation of negotiating support for the cipher's key exchange a potentially asynchronous operation. The spec needs to be clear that the correct route is to spend the RTT to fetch the key rather than to resort to a low priority plain PSK suite. Right now, it's ambiguous as to whether the server should request a retry and negotiate a (EC)DHE suite or negotiate plain PSK in this scenario.

On additional thought, this also affects ECDHE vs. DHE. If ECDHE is a higher priority, but no key was provided, but a key is possible, it should kick of a HelloRetryRequest rather than go down the list to a DHE. Not doing so here, however, isn't that much of a problem. They both have PFS; plain PSK doesn't.

**Comment by davegarrett** [comment]
There can be another hiccup if a client were to (stupidly) offer groups with a high priority group not getting its key sent, but lower priority group(s) getting their key(s) sent. If the prioritization is to be respected fully, it should fetch the highest mutually supported group's key rather than using a lower priority, but already available, one. This is fixable by just making sure all groups with keys sent in the first flight are at a higher priority than the other supported groups.

**Comment by ekr** [comment]
I don't think we should be dictating the server's policy here. If the client wants ECDHE it can force it, just as the server can. Feel free to raise this issue on-list if you disagree. In the meantime I'm marking it parked.

**Comment by davegarrett** [comment]
This edge case was a possible result of PSK cipher suite prioritization that is no longer applicable in the new negotiation that lacks them. Closing.
