### ISSUE TITLE
Version in additional data

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#278]
The additional data covers:
       additional_data = seq_num + TLSPlaintext.record_version

However TLSPlaintext.record_version is now a fixed field {3, 1}.
We have two sensible options here:

1. Remove the record_version as an input
2. Use the actual protocol version.

I lean towards option 2, but I could do either.

**Comment by davegarrett** [comment]
The version is already mixed into the keygen. I see no reason to keep it in the AD.

**Comment by briansmith** [comment]
There is a third sensible option: Just keep doing the same thing that TLS 1.2 did, so that we don't have to add more complexity to implementations that need to support both TLS 1.3 and TLS 1.2. This is what I prefer.

**Comment by davegarrett** [comment]
On Monday, October 05, 2015 07:59:10 pm Brian Smith wrote:
> There is a third sensible option: Just keep doing the same thing that TLS 1.2 did, so that we don't have to add more complexity to implementations that need to support both TLS 1.3 and TLS 1.2. This is what I prefer.

It's already different, though.

TLS 1.2:
    additional_data = seq_num + TLSCompressed.type +
                        TLSCompressed.version + TLSCompressed.length;
TLS 1.3:
    additional_data = seq_num + TLSPlaintext.record_version

Dropping the version makes the new version simpler with no downside. Keeping it means that additional_data still needs to be computed, rather than just being equivalent to the seq_num.

The length was removed for a specific reason, noted in the current draft:
> Note: In versions of TLS prior to 1.3, the additional_data included a length field. This presents a problem for cipher constructions with data-dependent padding (such as CBC). TLS 1.3 removes the length field and relies on the AEAD cipher to provide integrity for the length of the data.

If it's going to be different, it may as well be the simplest different.

**Comment by briansmith** [comment]
> If it's going to be different, it may as well be the simplest different.

I agree.

**Comment by davegarrett** [comment]
It just needs to make sure it's clear that TLSPlaintext.record_version MUST be ignored and for all we care it could be modified by an intermediary because it's irrelevant.

Just to cross-link the obviously better route: issue #144. If viable, just ditching the useless fields entirely is simplest.

**Comment by ekr** [comment]
Removing the field doesn't answer the question of whether it should be MACed or not.

For instance, we MAC the sequence number even though it's not carried inline.

**Comment by ekr** [comment]
@seanturner I think we have consensus to remove the version number here. @martinthomson do you want to file a separate issue to remove the sequence #?
