### ISSUE TITLE
swap order of EC and RSA in MTI cipher suites

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#279]
(no hat)

I would like to humbly suggest that we swap the order of listed MTI algorithms in Section 8.1 to put ECDSA first.  I have this vague and completely unsubstantiated notion that it would be better for the future to put the ECDSA algorithms first.  Also, I kind of remember the conversation at the Spring TLS Interim meeting in Seattle going something like "EC, EC, EC, EC!" and the "oh yeah we also have to do RSA".

OLD:

the musts

       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

the shoulds:

       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

NEW:

the must:

       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

the shoulds:

       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by ekr** [comment]
Doneish.
