### ISSUE TITLE
Depreciation of various kinds 

### ISSUE THREAD

**Issue by wbl** [tlswg/tls13-spec#28]
TLS 1.2 currently supports a number of ciphersuites and mechanisms that are little-used or outdated. In particular SHA-1, MD5, RC4, DSA with any modulus size, RSA with small moduli. Some of these will get chopped out as a result of other issues, but others will not.

**Comment by davegarrett** [comment]
Dependencies:
SHA1: PR #231
MD5: PR #188
RC4: PR #107
DSA: PR #235
weak RSA: PR #167

Statuses:
the pending PR #231 drops SHA1 to SHOULD NOT
MD5 is currently MUST NOT & PR #231 also adds a MUST always error if seeing it
RC4 is currently a MUST NOT
DSA is pending decision & discussion on-list (issue #222; PR #235)
weak RSA is currently considered "not appropriate" with the following text:
> "certificate chains containing keys or signatures weaker than 2048-bit RSA or 224-bit ECDSA are not appropriate for secure applications"

Merging the pending PRs listed as dependencies above should be sufficient to close this issue.

**Comment by ekr** [comment]
This is done
