### ISSUE TITLE
sha1 in s6.3.2.1

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#280]
I think sha1 is supposed to be removed from this?  If not, the int is missing sha2.

   enum {
       none(0),
       sha1,
       sha256(4), sha384(5), sha512(6),
       (255)
   } HashAlgorithm;

**Comment by ekr** [comment]
No, it's there because you can offer it for certs. It is missing the assignment. PRs welcome :)

**Comment by seanturner** [comment]
Okay so it's just missing the "(2)".  I'll get on the PR.

**Comment by beurdouche** [comment]
Fixed by PR #286
