### ISSUE TITLE
Be consistent about the use of "_RESERVED"

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#281]
There are a couple of times the reserved values don't include the string "_RESERVED".  Can we either note this in the intro or add "_RESERVED" to the appropriate places in ContentType and HandshakeType:

      Appendix A.  Protocol Data Structures and Constant Values

      This section describes protocol types and constants.  Values listed
      as _RESERVED were used in previous versions of TLS and are listed
      here for completeness.

      enum {
          reserved(0),
          reserved(20), alert(21), handshake(22),
          application_data(23), early_handshake(25),
          (255)
      } ContentType;

      enum {
          reserved(0), client_hello(1), server_hello(2),
          session_ticket(4), hello_retry_request(6),
          server_key_share(7), encrypted_extensions(8),
          certificate(11), reserved(12), certificate_request(13),
          reserved(14), certificate_verify(15), reserved(16),
          server_configuration(17), finished(20), (255)
      } HandshakeType;

**Comment by beurdouche** [comment]
If we can remove all the fields suffixed by `_RESERVED` it would make the enums more easy to read. =)
