### ISSUE TITLE
Section "4.9.1. Digital Signing" does not state salt length for RSA-PSS signatures

### ISSUE THREAD

**Issue by ttaubert** [tlswg/tls13-spec#291]
The RSA-PSS salt length seems to be missing from the specification. The original post on the mailing list and a few other sources propose that `saltLength := hLen` where `hLen` is the length of the digest output in bytes.

Should this be raised on the mailing list again or was this agreed on already?

**Comment by ekr** [comment]
Let's just do it the way you propose. PR welcome
