### ISSUE TITLE
Close client's 0-RTT application data with close_notify

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#295]
This seems obvious. Otherwise it's trial decryption FTW.

**Comment by martinthomson** [comment]
Will there be an exception for the encrypted content type so that a server can find the close_notify when it doesn't have the keys?

**Comment by ekr** [comment]
I don't think so. We already agreed in Prague that trial decryption was OK for the  transition from failed 0-RTT to 1-RTT.

**Comment by davegarrett** [comment]
If trial decryption is considered OK here, please make sure that's noted explicitly wherever applicable.
