### ISSUE TITLE
CELLOS: O-RTT 1

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#306]
It is not clear whether the server can send [ApplicationData] before receiving client {Finished}. (This is prohibited only if client authentication is used.) If this is not allowed, the client can receive [Application Data] only after sending {Finished} and needs two rounds for receiving the server's data. In this case "0-RTT" has no advantage over the full-handshake with respect to latency because in the full-handshake the client can receive the server's data in two rounds by sending the client's {Finished} and [ApplicatiomData] at the same time.

Solution proposed: Explicitly allow the server to send application data before receiving Client Finished. Also consider to allow this in case of client authentication is used.

**Comment by ekr** [comment]
This will be fixed in a forthcoming version.

**Comment by ekr** [comment]
Closing, because redundant with upcoming changes.
