### ISSUE TITLE
CELLOS: 0-RTT 3

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#308]
It is not clear how we can avoid replay attack in 0-RTT.

Solution proposed:

Add how we can avoid replay in 0-RTT:
- Check freshness of the random value in ClientHello, or
- Verify client {Finished}, which contains server's random in ServerHello.

**Comment by ekr** [comment]
This doesn't work without global state. See:
http://www.ietf.org/mail-archive/web/tls/current/msg15594.html
