### ISSUE TITLE
CELLOS: Resumption & PSK 1

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#309]
Note that the client supplies a ClientKeyShare to the server as well, which allows the server to decline resumption and fall back to a full handshake." Here PSK is ignored.

Solution proposed: Replace this sentence by "Note that the client supplies a ClientKeyShare to the server as well, which allows PSK + (EC)DHE or the server to decline resumption and fall back to a full handshake"

**Comment by ekr** [comment]
PR welcome.

**Comment by ekr** [comment]
Already fixed.
