### ISSUE TITLE
HKDF generates invalid master secret length?

### ISSUE THREAD

**Issue by zakar** [tlswg/tls13-spec#338]
https://tlswg.github.io/tls13-spec/#key-schedule says master secret is generated by

master_secret = HKDF-Extract(mSS, mES)

The master secret length depends on the underlying hash function. So if the the hash function's output length is not 48bytes, then master secret is not 48bytes. It's conflicted with the master secret length specifiied in SecurityParameters (https://tlswg.github.io/tls13-spec/#connection-states)

And https://tlswg.github.io/tls13-spec/#cipher-suites says HKDF should used with hash function specified in ciphersuite. So if the a ciphersuite use sha256, the master secret won't be 48bytes.

**Comment by ekr** [comment]
The master secret isn't going to be 48 bytes any more. I just haven't gotten to editing that section of the spec. Thanks.

**Comment by zakar** [comment]
So is there any length restriction for master secret? It's totally depends on the length of the underlying hash function?

**Comment by ekr** [comment]
Pretty much. Though I would expect us not to standardize hash functions
with much shorter lengths.

**Comment by ekr** [comment]
Fixed by removing SecurityParamerts
