### ISSUE TITLE
Editorial: used of early_handshake in 6.3.2.5. Early Data Indication 

### ISSUE THREAD

**Issue by huitema** [tlswg/tls13-spec#340]
The early data indication parameters are defined as client_authentication(1), early_data(2), and client_authentication_and_data(3). A few paragraph after that, some text refers to them by what was probably an old name: 
   If TLS client authentication is being used, then either "early_handshake" or "early_handshake_and_data" MUST be indicated in order to send the client authentication data on the first flight. 
Easy fix...

**Comment by ekr** [comment]
See https://github.com/tlswg/tls13-spec/pull/373

**Comment by ekr** [comment]
This should now be fixed.
