### ISSUE TITLE
Add a privacy considerations section describing linkage values

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#343]
1. Tickets
2. ServerConfiguration values
3. Cookies

**Comment by jsalowey** [comment]
Is it appropriate to consider the similar issue of fingerprinting an implementation?

**Comment by ekr** [comment]
@dkg you were going to provide?

**Comment by ekr** [comment]
@dkg you promised to do this back in B-A.

**Comment by ekr** [comment]
I think this is actually adequately covered by the current text.
