### ISSUE TITLE
32bit (seconds since UNIX epoch): expiration_date in ServerConfiguration

### ISSUE THREAD

**Issue by hannesm** [tlswg/tls13-spec#348]
As far as I can see, the only timestamp used is `expiration_date` in the ServerConfiguration (apart from X.509 validity checks which require synchronised clocks).  This is defined as seconds since UNIX epoch, and will overflow sooner than later.  Maybe either use a relative amount of seconds here, or expand to a 64bit value!?

I suggest to use 32bit network byte order (same as `ticket_lifetime_hint`), which value are the seconds how long this configuration is valid, and thus may be cached for at most this amount of seconds.

**Comment by songdongsheng** [comment]
We don't expect that TLS 1.3 can live to year 2106.

**Comment by hannesm** [comment]
discussion on the mailing list https://www.ietf.org/mail-archive/web/tls/current/msg18403.html
