### ISSUE TITLE
fix Bleichenbacher attack reference

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#358]
Currently, the "FI06" reference links to:
http://www.imc.org/ietf-openpgp/mail-archive/msg14307.html
Link text is:
"Bleichenbacher's RSA signature forgery based on implementation error"

This is now 404. It should be replaced with a working link, preferably one other than a mailing list archive.

Also, it's missing the leading quotation mark, which can get fixed at the same time.

**Comment by satokan** [comment]
Here is the new link;
https://www.ietf.org/mail-archive/web/openpgp/current/msg00999.html
