### ISSUE TITLE
KAT values for key derivation

### ISSUE THREAD

**Issue by jfigus** [tlswg/tls13-spec#378]
It would be good to provide an appendix that included KAT values for the key derivation logic.  These KAT values should include the intermediate values for xSS, xES, mSS, mES, master_secret, etc.

**Comment by ekr** [comment]
I think this would be useful, but actually I think we should provide a whole handshake transcript.

I wonder if this should be a separate draft.

**Comment by jfigus** [comment]
That would be useful too.  But there are so many variations in the handshake messages (e.g. extension values), it may be a lot to sift through.  The KDF is fairly self-contained and is an area that typically is harder to troubleshoot during the implementation process, compared to the handshake messages that can be easily sniffed off the wire.  For instance, if the key_block is miscalculated, having the intermediate values for xSS, mSS, etc. is very helpful to determine which phase of the KDF has failed.

**Comment by ekr** [comment]
Sorry, what I meant was to provide a full transcript plus the intermediate values.

**Comment by hannesm** [comment]
We're [nqsb.io](https://nqsb.io) (@pqwy and @hannesm) are working on an automated conformance checker exploring the state space for TLS 1.3 (which we submitted as a proposal to TRON, where we will also present working code and tools, currently work in progress).  Likely, it will also be able to dump the full handscript transcript including intermediate states.  We will hopefully resolve discrepancies of the interpretation of the RFC between our model/implementation and others early.  (This can be an addition to some statically written handshake transcripts.)

**Comment by jfigus** [comment]
Here's my first attempt at implementing the KDF (https://github.com/jfigus/s2n).  I realize this section of the draft is changing and these KAT values may not be useful yet.  But if anyone is interested...

Handshake type:  1-RTT
Handshake hash:  SHA-256

SS/ES: 
    4b d0 af e6 49 8b c0 ec 66 34 5b 8f 01 24 78 90 
    ae cd 83 11 ac 5e a3 30 dd c0 d5 6b a1 4f 60 08 
handshake_hash: 
    18 87 12 7f fa 7b 29 02 7d 08 68 06 75 65 b0 82 
    47 2d 96 83 c3 4a a1 92 60 20 1c 20 82 54 51 55 
xSS: 
    79 32 3e 23 93 e0 79 39 05 2d 36 b7 52 6b 6f 2d 
    f0 87 e5 03 57 ba c9 32 e5 08 ec 16 39 9e de 9d 
mSS: 
    86 d3 89 1a 54 93 c7 a7 45 09 ff f4 42 ee 32 21 
    eb 92 bd 11 7d 20 c2 f2 e2 60 aa 0d ca c8 b8 a4 
mSS: 
    e1 f7 18 33 9d e3 eb 32 15 64 03 37 da 95 29 3d 
    03 c0 41 91 2f a9 61 4d ad f4 8b 20 a3 1b 20 9f 
master_secret: 
    e1 86 8f 0e 17 86 80 00 ee d6 34 c1 65 2e 08 1e 
    f2 01 78 e5 29 0d 48 36 c3 c3 f1 bc 02 ca 28 c3 
finished_secret: 
    86 02 cf 88 65 d0 de 62 de 3e 3c 55 e0 41 20 85 
    1b 94 02 97 41 41 d2 bd de 4f 99 91 f5 28 3c f5 
application_keyblock: 
    8a 18 35 42 fe c2 a5 7b 47 4d 63 52 a7 a9 b5 71 
    9c df a2 7d 68 8a 28 80 ab ef 59 cc 3b bb ee 2e 
    2f cc 75 08 c7 61 6d f4 b6 cb 6b da 64 cf a3 c7 
    c0 ea 31 56 dd db 9b fc e8 76 01 87 ef db 85 3b 
    33 87 73 b5 b8 0c 33 56 be 92 87 a8 e8 b6 b5 80 
    2e 8a af 9f ff 17 60 69 51 6c d9 65 a1 f2 96 3e 
    e5 40 82 f9 21 d1 b3 ff 1d fe 61 c0 7e 76 d0 c6 
    e8 48 ab 2f 7b 29 ef 6c 41 fd 5e 32 26 c5 39 49

**Comment by hannesm** [comment]
while I get the same for `xSS` and `xES`, my derivation differs in `mSS` already.  input to `HKDF.expand` (which works with RFC5869 tests) is:

```
HkdfLabel:
00 20 1f 54 4c 53 20 31 2e 33 2c 20 65 78 70 61
6e 64 65 64 20 73 74 61 74 69 63 20 73 65 63 72
65 74 20 18 87 12 7f fa 7b 29 02 7d 08 68 06 75
65 b0 82 47 2d 96 83 c3 4a a1 92 60 20 1c 20 82
54 51 55
```
```
mss:
f8 31 e3 2f 71 79 e4 9f 81 be 3c 6a 8e a9 3f a5
96 a4 e1 fc 0e d9 2c e6 72 ec cd 75 17 c4 ec c2
```

**Comment by jfigus** [comment]
Are you implementing to revision 11 of the draft?  Revision 10 was still the latest when I posted these KAT values.  It looks like HkdfLabel is now defined different in revision 11.  The label now comes before the hash value in the byte stream.

The first two octets of your HkdfLabel are 0020, which is the length of HkdfLabel.  This is 32 bytes in your case, but you've provided 67 bytes of output for HkdfLabel.  You may want to take a closer look at this.

The hex stream for "expanded static secret" is:
65 78 70 61 6e 64 65 64 20 73 74 61 74 69 63 20 73 65 63 72 65 74
which appears to start at the 13th octet in your HkdfLabel.  Shouldn't this start at the 4th octet?

**Comment by hannesm** [comment]
(ups, replied directly to john). yes, I'm working on draft-11

* length: from the draft `HkdfLabel.length is Length` -- where `Length` is an argument (`L`, the digest size of the hash function, in this case 32 bytes) -- is this supposed to be the length of the `HkdfLabel` struct?  It should be clarified.

* expanded static secret: `HkdfLabel.label is "TLS 1.3, " + Label` -- I read this as the label in `HkdfLabel` should then be `TLS 1.3, expanded static secret`

**Comment by jfigus** [comment]
Yes, I missed the "TLS 1.3, " prefix to the label.  Good catch.  

I'm still confused on the HkdfLabel.length.  The spec does say "HkdfLabel.length is Length".  But the spec does not define "Length".  It does define "L" as the length of the hash function.  Are we to assume that "L" and "Length" are the same?  Given that HkdfLabel contains two opaque values, and an opaque value begins with the length, setting HkdfLabel.length to L seems redundant.  I was interpreting "Length" to be the length of the HkdfLabel, not L.

**Comment by jfigus** [comment]
Here are new values with the fixes you identified...

handshake_hash: 
    18 87 12 7f fa 7b 29 02 7d 08 68 06 75 65 b0 82 
    47 2d 96 83 c3 4a a1 92 60 20 1c 20 82 54 51 55 
SS/ES: 
    4b d0 af e6 49 8b c0 ec 66 34 5b 8f 01 24 78 90 
    ae cd 83 11 ac 5e a3 30 dd c0 d5 6b a1 4f 60 08 
xSS: 
    79 32 3e 23 93 e0 79 39 05 2d 36 b7 52 6b 6f 2d 
    f0 87 e5 03 57 ba c9 32 e5 08 ec 16 39 9e de 9d 
mss_HkdfLabel:
    00 43 1f 54 4c 53 20 31 2e 33 2c 20 65 78 70 61 
    6e 64 65 64 20 73 74 61 74 69 63 20 73 65 63 72 
    65 74 20 18 87 12 7f fa 7b 29 02 7d 08 68 06 75 
    65 b0 82 47 2d 96 83 c3 4a a1 92 60 20 1c 20 82
    54 51 55 
mSS: 
    61 63 fb a8 12 98 64 af 36 ff 4c cc f0 0b 51 22 
    f7 c9 36 67 34 f0 1d 19 d2 9f a8 19 a9 83 af da 
mes_HkdfLabel: 
    00 46 22 54 4c 53 20 31 2e 33 2c 20 65 78 70 61 
    6e 64 65 64 20 65 70 68 65 6d 65 72 61 6c 20 73 
    65 63 72 65 74 20 18 87 12 7f fa 7b 29 02 7d 08  
    68 06 75 65 b0 82 47 2d 96 83 c3 4a a1 92 60 20 
    1c 20 82 54 51 55 
mES: 
    14 fc 5e 90 20 a4 0b 69 00 1b ce b8 64 91 b6 56 
    e9 7c 44 c7 99 38 77 b8 5b ce af b9 1c 41 ef 70 
master_secret: 
    d5 61 f3 b3 18 8e 6d d3 a0 9d b3 ee 11 a9 7a 08 
    bf 83 d0 92 f6 27 92 10 5b 37 b0 14 d3 f6 da ce 
fs_HkdfLabel: 
    00 3c 18 54 4c 53 20 31 2e 33 2c 20 66 69 6e 69 
    73 68 65 64 20 73 65 63 72 65 74 20 18 87 12 7f 
    fa 7b 29 02 7d 08 68 06 75 65 b0 82 47 2d 96 83 
    c3 4a a1 92 60 20 1c 20 82 54 51 55 
finished_secret: 
    9c e6 9b 95 2e b8 3a 64 bf 7f 50 29 e7 6c b7 d8
    4a 07 be cd 23 91 e3 c4 4c b8 be 2f 78 e8 d9 bf 
app_HkdfLabel: 
    00 4b 27 54 4c 53 20 31 2e 33 2c 20 61 70 70 6c
    69 63 61 74 69 6f 6e 20 64 61 74 61 20 6b 65 79
    20 65 78 70 61 6e 73 69 6f 6e 20 18 87 12 7f fa
    7b 29 02 7d 08 68 06 75 65 b0 82 47 2d 96 83 c3
    4a a1 92 60 20 1c 20 82 54 51 55 
application_keyblock:
    a2 63 95 c4 fc a5 ae d8 e5 f5 c5 85 62 73 67 a4
    b2 b1 e3 38 91 6e 97 15 75 7c c6 54 ca 10 ad 11
    11 75 8a 4f c3 de 0a fb ba a8 59 85 0a fc f4 54
    b6 e2 3c e8 05 fc fb c7 b0 18 fb 73 af 92 7b b4
    43 f1 4c 94 54 9c e3 43 b9 32 58 bd 4b e2 e4 57
    4e f2 4e e4 18 2e 4c 3b 81 5c 7a bf ea 2e 04 37
    6e 8b db 90 ba af 43 3b 2f b3 79 60 d2 de ac 05
    3e 41 3c 90 37 c6 bb af 05 aa 1f 54 08 17 14 55

**Comment by ekr** [comment]
Length is the length of the output key.

**Comment by jfigus** [comment]
OK, I had it wrong.  Here are the updated KAT values...

handshake_hash: 
```
18 87 12 7f fa 7b 29 02 7d 08 68 06 75 65 b0 82
47 2d 96 83 c3 4a a1 92 60 20 1c 20 82 54 51 55 
```

SS/ES: 
```
4b d0 af e6 49 8b c0 ec 66 34 5b 8f 01 24 78 90
ae cd 83 11 ac 5e a3 30 dd c0 d5 6b a1 4f 60 08 
```

xSS: 
```
79 32 3e 23 93 e0 79 39 05 2d 36 b7 52 6b 6f 2d
f0 87 e5 03 57 ba c9 32 e5 08 ec 16 39 9e de 9d 
```

HkdfLabel: 
```
00 20 1f 54 4c 53 20 31 2e 33 2c 20 65 78 70 61 
6e 64 65 64 20 73 74 61 74 69 63 20 73 65 63 72
65 74 20 18 87 12 7f fa 7b 29 02 7d 08 68 06 75
65 b0 82 47 2d 96 83 c3 4a a1 92 60 20 1c 20 82
54 51 55 
```

mSS: 
```
f8 31 e3 2f 71 79 e4 9f 81 be 3c 6a 8e a9 3f a5
96 a4 e1 fc 0e d9 2c e6 72 ec cd 75 17 c4 ec c2
```

HkdfLabel: 
```
00 20 22 54 4c 53 20 31 2e 33 2c 20 65 78 70 61
6e 64 65 64 20 65 70 68 65 6d 65 72 61 6c 20 73
65 63 72 65 74 20 18 87 12 7f fa 7b 29 02 7d 08
68 06 75 65 b0 82 47 2d 96 83 c3 4a a1 92 60 20
1c 20 82 54 51 55 
```

mES:
```
e7 55 7c 57 47 21 ce 01 53 7a d9 d6 37 5a a9 73
1b 7e 8a 20 1d db 06 3f 98 70 ae 06 a0 e8 7b 67
```

master_secret: 
```
fe 8a 3e 40 f7 00 4a ea 18 26 e0 57 53 c8 a4 cd 
55 fa d5 f0 38 92 58 f5 45 03 21 64 14 71 6c 4e 
```

HkdfLabel: 
```
00 20 18 54 4c 53 20 31 2e 33 2c 20 66 69 6e 69
73 68 65 64 20 73 65 63 72 65 74 20 18 87 12 7f
fa 7b 29 02 7d 08 68 06 75 65 b0 82 47 2d 96 83
c3 4a a1 92 60 20 1c 20 82 54 51 55 
```

finished_secret: 
```
9b b0 9c 9f ca ea a2 86 11 86 f2 3e 41 d0 9c f6 
26 63 02 54 b1 da 41 63 3c 42 02 c7 c9 70 9c 7b 
```

HkdfLabel: 
```
00 80 27 54 4c 53 20 31 2e 33 2c 20 61 70 70 6c
69 63 61 74 69 6f 6e 20 64 61 74 61 20 6b 65 79
20 65 78 70 61 6e 73 69 6f 6e 20 18 87 12 7f fa
7b 29 02 7d 08 68 06 75 65 b0 82 47 2d 96 83 c3
4a a1 92 60 20 1c 20 82 54 51 55 
```

application_keyblock: 
```
9e e5 64 ef f3 d1 43 00 17 66 3e 32 9d a6 8a 07
b5 ea 4e c2 5b 21 af 56 a0 72 54 88 64 b3 c7 b9
e7 eb 18 4c 37 9e 1e 14 4b 30 e6 ca f6 95 27 66
19 6f 07 37 9b be 05 be 3e 7a 28 c5 73 ec 9c ea
22 b1 bb 61 2d 3d 29 6c b7 55 0b 8a 06 90 d1 99
e9 12 b4 5d 09 30 34 37 56 a4 f7 cb 4f e7 7c b1
d6 86 c5 bd 23 84 fb cc c0 b4 f9 32 04 ca 0f ad
91 49 94 68 ff 05 3c 47 00 4c 68 c5 6b 38 45 82
```

**Comment by ekr** [comment]
Conclusion is that this should go into a new document. @martinthomson to write
