### ISSUE TITLE
How to build the DigitallySigned for a CertificateVerify?

### ISSUE THREAD

**Issue by hannesm** [tlswg/tls13-spec#407]
In the draft, we have

```
   struct {
        digitally-signed struct {
           opaque hashed_data[hash_length];
        };
   } CertificateVerify;
```
`Where hashed_data is the hash output described in Section 6.3.4, namely Hash(Handshake Context + Certificate).`

where digitally-signed is defined:
`The signature is a digital signature using those algorithms over the contents of the element. The contents themselves do not appear on the wire but are simply calculated. The length of the signature is specified by the signing algorithm and key.`
`the contents of the element always start with 64 bytes of octet 32 in order to clear that chosen-prefix.`
`Following that padding is a context string used to disambiguate signatures for different purposes. The context string will be specified whenever a digitally-signed element is used. A single 0 byte is appended to the context to act as a separator.`
`Finally, the specified contents of the digitally-signed structure follow the 0 byte after the context string. (See the example at the end of this section.)`

Assuming  the raw handshake messages (client_hello .. certificate) to be `packets`, and `+` being concatenation. Should it be:
`Sign (Hash (64 * 0x20 + context + 0x0 + packets))`
OR
`Sign (Hash (64 * 0x20 + context + 0x0 + Hash(packets)))`

Thanks,

hannes

**Comment by ekr** [comment]
I use the second.
