### ISSUE TITLE
KeyShareEntry encoding

### ISSUE THREAD

**Issue by hannesm** [tlswg/tls13-spec#410]
To confirm my interpretation: a concrete KeyShare entry (ffdhe2048, share is 0xFFFF) would look like the following (hex encoded) `01 00 00 04 00 02 FF FF` (there is a 16 bit length field for the Key_exchange followed by another 16 bit length field for DH_y), one for secp256r1 (share 0xFF) would look like: `00 17 00 02 01 FF` (16 bit length followed by 8 bit length)?

**Comment by ekr** [comment]
Yes, I agree.

**Comment by hannesm** [comment]
thx
