### ISSUE TITLE
Should EncryptedExtensions have an inner list

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#419]
The document is written as:
      struct {
          Extension extensions<0..2^16-1>;
      } EncryptedExtensions;

This seems like it's a redundant length. Should we have it be
Extension extensions[TLSHandshake.length]

**Comment by ekr** [comment]
@davidben Thoughts?

**Comment by davidben** [comment]
*shrug* I don't hugely care either way.

I probably lean towards leaving it as is? It's all of two bytes. I suppose consistency would demand it stay there. Every other struct in TLS is self-delimiting, even though it costs length prefixes. That is, one could write:
```
struct {
  ClientHello client_hellos<0..2^24-1>
  ServerHello server_hellos<0..2^24-1>
} HelloList
```
even though it doesn't actually make much sense.

One could equally easily omit the length in `ServerHello.extensions` without being ambiguous. It's just a let messier to spell out. But it seems weird to cut it out only in `EncryptedExtensions`.

**Comment by ekr** [comment]
Sold, on the principle of avoiding unnecessary change.
