### ISSUE TITLE
Add encrypted NextRecordLength field to make next record's unencrypted header optional

### ISSUE THREAD

**Issue by bford** [tlswg/tls13-spec#422]
The Record Padding section currently adds a 1-byte encrypted trailer with the new encrypted content type.  Extend this encrypted trailer to include a "next record length" field just before encrypted content type and after record payload, which:
- If zero, indicates that the following TLS record starts with the usual 5-byte unencrypted header, with the record's length defined by that header.
- If nonzero, indicates the length of the AEAD-encrypted portion of the next TLS record, and suppresses the next record's 5-byte unencrypted header entirely.

This change permits TLS implementations that care about traffic analysis protection to hide record lengths and boundaries, making one long record cryptographically indistinguishable from several short records for example.  TLS implementations that that don't care can just always set this field to 0 for simplicity and retain complete legacy compatibility with TLS 1.2's unencrypted record format.

Background on mailing list:
- Proposal details: https://www.ietf.org/mail-archive/web/tls/current/msg18524.html
- Implementation in NSS: https://www.ietf.org/mail-archive/web/tls/current/msg18710.html

Thanks.

**Comment by ekr** [comment]
Parking this because of minimal WG interest.
