### ISSUE TITLE
Should it be possible to do 0-RTT with the server signing

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#443]
This would be nice to demonstrate key continuity. It's not entirely clear how to do this, but sense in B-A was that it was desirable. This is a placeholder bug so I don't forget.

**Comment by martinthomson** [comment]
I'll take an action to write a draft on this.  Some new cipher suites will be required with the design I have in mind.

**Comment by ekr** [comment]
Working on proposal for this
