### ISSUE TITLE
Can supported_groups be included in the server's EncryptedExtensions

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#450]
I can't see any reason why not.

**Comment by ekr** [comment]
This PR already landed.

**Comment by martinthomson** [comment]
Maybe you should look again:

supported_groups [RFC-ietf-tls-negotiated-ff-dhe] 	Yes 	Client

And I found no text on where the server is expected to send the extension.

**Comment by ekr** [comment]
https://github.com/tlswg/tls13-spec/commit/7e3f37f33ad4d70029e7216a17d2922a565d6c5a

**Comment by ekr** [comment]
https://github.com/tlswg/tls13-spec/commit/47a5f34a11d25dac1f9efbb64e711d57749b41d1
