### ISSUE TITLE
Apllication traffic keys don't derive from client Finished

### ISSUE THREAD

**Issue by svince** [tlswg/tls13-spec#452]
According to 7.1 Key Schedule, traffic_secret is derived from the handshake hash up to servers CertificateVerify. In 7.3 the application traffic keys are defined as:

key = HKDF-Expand-Label(traffic_secret,
                           “application data key expansion, client/server write key”,
                           handshake_context,
                           key_length)

where handshake_context is defined as the hash up to server Finished.
Therefore, these traffic keys are not derived from the client Finished.

So my question is if this is intented? If so, why?

**Comment by wbl** [comment]
Yes, it's intended. The reason is that the server can respond with application data ahead of the Client Finished, which is in a different flight from the Hello. Prohibiting this would introduce extra latency in a very common application scenario, namely HTTPs.

**Comment by svince** [comment]
Ok thank you for the explanation.
So the data sent in that flight, before receiving any client authentication message, is not yet guaranteed to be secure.
