### ISSUE TITLE
Derivation of traffic key has no intermediate HKDF-Extract

### ISSUE THREAD

**Issue by svince** [tlswg/tls13-spec#455]
The traffic key is derived by applying HKDF-Extract to the traffic_secret, which in turn is derived by applying HKDF-Extract to the master secret. There is no intermediate HKDF-Extract stage.

Is this intended?
Should there be an intermediate Extract stage?
Could the traffic key maybe be derived directly from the master secret, of course together with the correct handshake hash?

**Comment by ekr** [comment]
Sorry, which line are talking about? The traffic keys are derived by applying HKDF-Expand-Label to the current traffic secret:

http://tlswg.github.io/tls13-spec/#rfc.section.7.3

 key = HKDF-Expand-Label(Secret,
                           phase + ", " + purpose,
                           handshake_context,
                           key_length)

**Comment by svince** [comment]
According to [http://tlswg.github.io/tls13-spec/#rfc.section.7.3], the traffic key is computed like this:

key = HKDF-Expand-Label(Secret,
phase + ", " + purpose,
handshake_context,
key_length),
where Secret = traffic_secret

According to [https://tlswg.github.io/tls13-spec/#rfc.section.7.1], the traffic_secret is computed as follows:

traffic_secret_0 = HKDF-Expand-Label(master_secret,
                                          "traffic secret",
                                          handshake_hash, L)

The note at the end of 7.1 declares "each HKDF-Expand operation is paired with an HKDF-Extract".
But this is not the case for the traffic key, as there is no HKDF-Extract operation performed on traffic_secret.

Is this intended? If so, why?
Wouldn't it be the same (security wise) as directly using the master_secret to derive the traffic key?

**Comment by ekr** [comment]
Yes, that's an oversight. We are currently reworking the key schedule a bit (see https://github.com/tlswg/tls13-spec/pull/453) and that will have parity between extract and expand.

We could derive the traffic keys from MS, but then we would have to either precompute traffic_secret_1 (which is a bit odd) or keep MS around (which threatens PFS for resumed connections). So we did it this way.

**Comment by svince** [comment]
Okay thank you for the information. This helped.
