### ISSUE TITLE
Clarify interaction between 0-RTT and HelloRetryRequest

### ISSUE THREAD

**Issue by davidben** [tlswg/tls13-spec#456]
If the server's changed significantly between NewSessionTicket and the 0-RTT offer, it's possible that the client won't even have the right key_share. The server will then need to send HelloRetryRequest (and skip past any early data). What happens here is reasonably straightforward, but it probably should be mentioned explicitly that this can happen and, in that case, the second ClientHello should not have an early_data indicator.

**Comment by ekr** [comment]
Agreed. PR welcome :)

**Comment by ekr** [comment]
Fixed
