### ISSUE TITLE
0-RTT handshake with client side authentication?

### ISSUE THREAD

**Issue by svince** [tlswg/tls13-spec#497]
In Section 6.2.3 Figure 4 shows a handshake with 0-RTT data and the possibility of client side authentication (Certificate and CertificateVerify). However in Section 6.2.2, Figure 3, in the subsequent handshake, it is not shown that the client may need to authenticate itself. Do I miss something or is this not consistent?

**Comment by ekr** [comment]
We agreed to ban this in Berlin but I failed to remove it from the spec. PR wanted. @siyengar

**Comment by siyengar** [comment]
Ya I was going to send a pr once we land the other major renegotiation prs going on. I'll check out whether there would be any major conflicts with the existing prs

**Comment by ekr** [comment]
Already fixed, I think.
