### ISSUE TITLE
Make the PRF hardware module friendly

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#5]
Mike StJohns points out several ways in which the current PRF is inimical to clean hardware module design [in an email](http://www.ietf.org/mail-archive/web/tls/current/msg12094.html) and [in a draft](http://tools.ietf.org/html/draft-stjohns-tls-tls13-crypto-infra-00).

**Comment by briansmith** [comment]
Mike's suggestion is to base the KDF on SP800-108. However, I thought IETF decided to try to move new protocols to HKDF [1]. Selection of an SP800-108-based mechanism would require a clear justification for why it is used instead of HKDF.

[1] https://tools.ietf.org/html/rfc5869

**Comment by ekr** [comment]
Consensus at interim.

1. Label + length is enough.
2. Add:
    - length + label
    - all labels will now have "TLS 1.3, " in front of them.

**Comment by ekr** [comment]
Done
