### ISSUE TITLE
Hash Client's EncryptedExtensions and Finished when the Server picks PSK 0

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#501]
With the addition of `ticket_age`, we now require that the server process the client's EncryptedExtensions (and Finished) to determine whether it wants to process 0-RTT.  This means that the server is looking at things that aren't in the handshake transcript.  The temptation to use that data somehow to influence what is used in the final handshake is too much, we should not leave this footgun lying around.

Proposal:
Picking PSK 0 means that the server has the PSK that the client used for 0-RTT.  It might later indicate that it didn't accept the *data* that the client sent (by omitting `early_data_indication` from its `EncryptedExtensions`).  When the server indicates that it wants to use PSK 0, that means that it will have included the client's EncryptedExtensions and Finished in the session transcript.

**Comment by ekr** [comment]
Rendered moot by removal of EE.
