### ISSUE TITLE
cookie extension ID

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#534]
The cookie hello extension ID is currently assigned as 44, however the ticket age extension that was at 43 has been dropped, so there's a gap in the list of new IDs now. If we have no new extension to retake 43, cookie should probably be reassigned it to keep a contiguous set of IDs. Filing as an issue as this would be a notable wire-format change.

**Comment by ekr** [comment]
This doesn't seem like it makes life much better. Please take to the list if you want to make this change.

**Comment by ekr** [comment]
Oops. Didn't mean to close just yet.

**Comment by ekr** [comment]
I closed the gap with a different extension
