### ISSUE TITLE
Enforce HTTPS for the site itself

### ISSUE THREAD

**Issue by konklone** [tlswg/tls13-spec#538]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS: https://tlswg.github.io/tls13-spec/ 

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by ekr** [comment]
OK, I pushed the button.

**Comment by konklone** [comment]
:+1: :tada:
