### ISSUE TITLE
Allow empty TicketExtensions?

### ISSUE THREAD

**Issue by bifurcation** [tlswg/tls13-spec#539]
Right now it appears that the NewSessionTicket message is required to have at least one extension, whose body contains at least one byte.

```
 struct {
     TicketExtensionType extension_type;
     opaque extension_data<1..2^16-1>;
 } TicketExtension;

 struct {
     uint32 ticket_lifetime;
     uint32 flags;
     uint32 ticket_age_add;
     TicketExtension extensions<2..2^16-2>;
     opaque ticket<0..2^16-1>;
 } NewSessionTicket;
```

This seems silly, given that there are no extensions defined in this document.  Seems like the lower bounds should just be zero.

**Comment by ekr** [comment]
Fixed
