### ISSUE TITLE
Specify key_exchange as a fixed-length vector

### ISSUE THREAD

**Issue by s-zanella** [tlswg/tls13-spec#553]
~~I believe current implementations of Draft 13 don't include the length of the `key_exchange` field when serializing a `KeyShareEntry` struct to the wire. But `key_exchange` is specified as a variable-length vector (https://tlswg.github.io/tls13-spec/#key-share), so technically they should.~~

**Edited**: _Karthik pointed out to me that only the inner length, which was clearly redundant, was dropped in Draft 13. So there is no need for a fix, but there is an opportunity for some savings by changing the encoding of shares._

PR #462 changed the text to require padding DH shares to the length of the group, making communicating the length redundant. We could save 2 bytes per share and some processing for parsing and checking the length by specifying `key_exchange` as a fixed-length vector with a length dependent on the `group` field. This could also be done for ECDH shares since their length is determined by the curve (because any given curve must specify a single point format).

I don't know exactly what is the proper syntax to use, but what I mean is something like this:
```
 struct {
       NamedGroup group;
       select (NamedGroup):
           case ffdhe2048: opaque key_exchange[256];
           case ffdhe3072: opaque key_exchange[384];
           ...
           case secp256r1: opaque key_exchange[65];
           case secp384r1: opaque key_exchange[97];
           ...
   } KeyShareEntry;
```

**Comment by martinthomson** [comment]
The problem with this is that a new named group will have an indeterminate length.  The current design is fine.

**Comment by ekr** [comment]
Concur with MT's analysis.

**Comment by s-zanella** [comment]
A new named group will have an *indeterminate but fixed* length, so the 2-byte length will still be redundant. 
The `KeyShareEntry` struct can be extended as needed for new named groups.

The problem I see with redundancy is that implementations will have to check that the length field is consistent with the expected length determined by the group. Implementations will be tempted to omit parsing the length and doing this check.

I haven't found any security concern with ignoring the 2-byte length, but being free to choose 2 arbitrary bytes sounds like a bad design. 

In brief, what I'm suggesting is to either

1.  remove the redundant length bytes by changing the encoding of `KeyShareEntry`, or 
2. make a MUST for implementations to check that the length bytes encode the expected length

**Comment by wbl** [comment]
This proposal doesn't work. An old implementation that encounters an unknown new group needs to know the length of data it needs to skip.

**Comment by s-zanella** [comment]
Fair enough, you're right.

Then, would it be ok for an implementation that encounters a share from a known group and uses it to ignore the 2-byte length?

**Comment by martinthomson** [comment]
Failing to check values leads to bugs.  c.f. Heartbleed for an extreme example.  Implementations that encounter a 37 octet P-256 share should probably reject that message, but they are not obligated to do so if they aren't using the share.
