### ISSUE TITLE
Hash forking for post-handshake authentication

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#573]
It makes sense for the initial handshake to include the CertificateRequest, because it's in the sequence, but when doing post-handshake authentication, you have to snapshot the hash.  It would be easier if the handshake context is separated.  For CertificateVerify, this would be easier to manage:

```
Hash(HandshakeContext) + resumption_context + Hash(CertificateRequest + Certificate)
```

Similarly, for Finished:

```
Hash(HandshakeContext) + resumption_context + Hash(CertificateRequest + Certificate + CertificateVerify)
```

(I've taken David Benjamin's point about redundant hashing of the resumption context into account here.)

**Comment by ekr** [comment]
I don't think this is a good change. It's not hard to build hash implementations that can be forked, and this creates inconsistency.

**Comment by ekr** [comment]
Martin, I am closing this. Feel free to raise on the list.
