### ISSUE TITLE
Lock down TLS 1.2 {Hash,Signature}Algorithm registries

### ISSUE THREAD

**Issue by davidben** [tlswg/tls13-spec#574]
(Well, I think, strictly speaking, we need only lock down HashAlgorithm.)

The SignatureScheme change assumes that we will never again allocate new values in the TLS 1.2 HashAlgorithm and SignatureAlgorithm ranges. I'm not sure how to write that kind of IANA consideration or I'd put together a PR. The end result should probably be something like s/Unassigned/Reserved for TLS 1.3 compatibility/. From TLS 1.3 onwards, all new signature algorithms that apply to TLS 1.2 must go through a backported SignatureScheme.

(If we're not happy with that strong of a restriction, we could perhaps only burn HashAlgorithms 0x80 and up. Then TLS 1.3 SignatureSchemes live in the 0x8000 to 0xfdff range. Though #557's PSS text already implies we'll be backporting SignatureSchemes, so the division probably isn't necessary? I dunno. I don't really care either way.)

**Comment by ekr** [comment]
Let's just lock down HAshAlgorithm. Can you submit a PR?
