### ISSUE TITLE
NewSessionTicket message modification

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/tls13-spec#577]
Appendix A.3.4. lists the NewSessionTicket message as follows:

> enum { (65535) } TicketExtensionType;

> struct {
     TicketExtensionType extension_type;
     opaque extension_data<1..2^16-1>;
 } TicketExtension;

> enum {
   allow_early_data(1),
   allow_dhe_resumption(2),
   allow_psk_resumption(4)
 } TicketFlags;

> struct {
     uint32 ticket_lifetime;
     uint32 flags;
     uint32 ticket_age_add;
     TicketExtension extensions<0..2^16-2>;
     opaque ticket<1..2^16-1>;
 } NewSessionTicket;

I believe the structure should be defined as follows:

> enum {
   allow_early_data(1),
   allow_dhe_resumption(2),
   allow_psk_resumption(4), 
   (255)
 } TicketFlags;

> struct {
     uint32 ticket_lifetime;
     TicketFlags flags;
     uint32 ticket_age_add;
     TicketExtension extensions<0..2^16-2>;
     opaque ticket<1..2^16-1>;
 } NewSessionTicket;

32 bits for the flags feels a bit too long to me and the currently defined NewSessionTicket structure does not use the TicketFlags enum.

**Comment by ekr** [comment]
This was restructured, so closing
