### ISSUE TITLE
description for encoded vector

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#587]
In s3.4 there's this sentence:

    The length of an encoded vector must be an even multiple of the length of a single element (for example, a 17-byte vector of uint16 would be illegal).

An errata for 5246 was filed (http://www.rfc-editor.org/errata_search.php?rfc=5246&eid=4750) suggesting this fix:

    The length of an encoded vector must be a whole multiple of the length of a single element (for example, a 17-byte vector of uint16 would be illegal).

Ben Kaduk pointed out that Jeff Hodges suggested this earlier:

    The length of an encoded variable-length vector must be an exact multiple of the length of a single element. For example, an encoded 17-byte vector of uint16 would be illegal, and an encoded variable-length vector of four 32 byte elements, having a ceiling of 2^16-1, will be 130 bytes long overall (2 byte length field followed by 128 bytes of data).

Should we leave as is or adopt one of the two suggestions?

**Comment by ekr** [comment]
I would be willing to have "whole" but I think "even" is fine in this
context.
