### ISSUE TITLE
ke_modes and auth_modes have opposite order in NST and PSK xtns

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#603]
struct {
         uint32 ticket_lifetime;
         PskKeyExchangeMode ke_modes<1..255>;
         PskAuthenticationMode auth_modes<1..255>;
         opaque ticket<1..2^16-1>;
         TicketExtension extensions<0..2^16-2>;
     } NewSessionTicket;

       struct {
           PskKeyExchangeMode ke_modes<1..255>;
           PskAuthenticationMode auth_modes<1..255>;
           opaque identity<0..2^16-1>;
       } PskIdentity;

**Comment by ekr** [comment]
Swap one

**Comment by davegarrett** [comment]
Huh? Both go ke_modes then auth_modes.

**Comment by ekr** [comment]
Huh, this must be a cut-and-paste error in my code.
