### ISSUE TITLE
Syntax issues

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#630]
I have written a syntax validator to check the validity of definitions. In this issue, I would like to point out what I noticed.

**Comment by kazu-yamamoto** [comment]
(1) Some enum definitions use "floor..ceiling" notation which is not defined. Section 3.5 should clearly define this.

**Comment by kazu-yamamoto** [comment]
(2) I think that the `struct` keyword is allowed only in the top level definitions. But `struct {}` is used inside of EarlyDataIndication. I would suggest to defined the following in the top level:

```
struct {} None;
```

**Comment by kazu-yamamoto** [comment]
(3) The following assignment is really strange:

```
struct {
    ContentType opaque_type = application_data(23); /* see TLSInnerPlaintext.type */
```

I would suggest to change this to:

```
struct {
    ContentType opaque_type = { 23 }; /* application_data, see TLSInnerPlaintext.type */
```

**Comment by davegarrett** [comment]
On Wednesday, September 07, 2016 04:24:15 am Kazu Yamamoto wrote:
> (3) The following assignment is really strange:
> 
> ```
> struct {
>     ContentType opaque_type = application_data(23); /* see TLSInnerPlaintext.type */
> ```
> 
> I would suggest to change this to:
> 
> ```
> struct {
>     ContentType opaque_type = { 23 }; /* application_data, see TLSInnerPlaintext.type */
> ```

I don't understand why you consider this current notation here strange. It's the same notation used for enum values elsewhere.

**Comment by kazu-yamamoto** [comment]
What I can tell from Section 3 is as follows:

- The "symbol(num)" notation is allowed in the *declaration* of enum.
- "symbol" can be used as *label* of the case clause.
- "{num, ...}" can be used for assignment.

I don't see that "symbol(num)" can be used for assignment.

I wrote a parse based on Section 3 and what I reported here is the errors reported by the parser.
