### ISSUE TITLE
KeyUpdate is missing in Appendix A

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#631]
"%%% SOMETHING" is necessary before the definition of `KeyUpdate`. Since I don't know what is appropriate for SOMETHING, I don't send a pull request.

**Comment by davegarrett** [comment]
"%%% Key Exchange Messages" with an empty line after it before the struct, would fit.

I'd suggest we just drop it, but PR #611 is giving it a member to make it worth not just stating it with a sentence instead.
