### ISSUE TITLE
Require extensions to be either encrypted or not encrypted

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#66]
"      The EncryptedExtensions message simply contains any extensions
      which should be protected, i.e., any which are not needed to
      establish the cryptographic context.  The same extension types
      MUST NOT appear in both the ServerHello and EncryptedExtensions.
      If the same extension appears in both locations, the client MUST
      rely only on the value in the EncryptedExtensions block.  [[OPEN
      ISSUE: Should we just produce a canonical list of what goes where
      and have it be an error to have it in the wrong place?  That seems
      simpler.  Perhaps have a whitelist of which extensions can be
      unencrypted and everything else MUST be encrypted.]]
"

**Comment by ekr** [comment]
Looking through the IANA list, it seems to me that the only extension which
has a case for being in ServerHello is 
supported_groups (really only needed for HelloRetryRequest, but probably
safest to put in both places) and ServerKeyShare if we extensionify it.
Am I missing any? @martinthomson, thoughts?

**Comment by martinthomson** [comment]
You might want to make a statement about encrypted extensions in general, noting that other than the following, extensions MUST be encrypted unless this is the client's first flight (and 0RTT is enabled):

key_share
supported_groups*
server_name (we discussed having an encrypted_server_name extension if this needed to be encrypted)

Other than that, you basically only need the parameters that determine a) routing, or b) key exchange.
I agree that you could encrypt supported_groups, but it doesn't seem like it is even needed in a ServerHello, you could even remove it.

I've heard people suggest that they might route on ALPN.  That would suggest a rule much like server_name.  And maybe an encrypted_alpn extension to match.

**Comment by ekr** [comment]
On Sun, Oct 4, 2015 at 1:49 PM, Martin Thomson <notifications@github.com>
wrote:

> You might want to make a statement about encrypted extensions in general,
> noting that other than the following, extensions MUST be encrypted unless
> this is the client's first flight (and 0RTT is enabled):
>

Note: we haven't added client type B extensions, so all client extensions
are unencrypted presently.

key_share
> supported_groups*
>
You need supported groups unencrypted in the ClientHello so the server can
process it.
It doesn't need to be encrypted in the ServerHello but it does need to be
sent by the
server so that the client can choose a key for client auth.


- In the Server

**Comment by ekr** [comment]
Duplicated by #72
