### ISSUE TITLE
Other syntax issues

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#660]
1. There is no definition for `Hash`.  I would like to know the type of `Hash.length` at least.
2. Should we use `select` for `TicketExtension.extension_data`, `Extension.extension_data`, `TLSPlaintext.fragment`, and `TLSInnerPlaintext.content`? If we do it, we can verify the coverage of enum types by parsers.

**Comment by kazu-yamamoto** [comment]
I did it for testing and I think the spec gets much readable. But I found one issue. For instance, if we change

```
struct {
    ExtensionType extension_type;
    opaque extension_data<0..2^16-1>;
} Extension;
```

to

```
struct {
    ExtensionType extension_type;
    select (Extension.extension_type) {
        case supported_groups:     NamedGroupList;
        case signature_algorithms: SignatureSchemeList;
        case key_share:            KeyShare;
        case pre_shared_key:       PreSharedKeyExtension;
        case early_data:           EarlyDataIndication;
        case supported_versions:   SupportedVersions;
        case cookie:               Cookie;
    };
} Extension;
```
length information is lost.

Note that this change provides benefit particularly to this `Extension` because the case names are differrent from the corresponding type names.

**Comment by ekr** [comment]
This is not an OK change. It would make it impossible to process unknown extensions.

**Comment by ekr** [comment]
Yeah, I don't think these are helping things much.

**Comment by davidben** [comment]
A handshake message in TLS may be fragmented across several records anyway, so there is no more descriptive thing to put there than an opaque byte string. In general, record boundaries and subprotocol message boundaries need not be correlated. The record payload is treated as a stream, with record boundaries discarded, and then parsed anew to get message boundaries. (Except for alerts and the points where handshake message boundaries induce key changes.)

**Comment by kaduk** [comment]
> what about Hash?

The question of length is addressed in

```
   The Hash function and the HKDF hash are the cipher suite hash
   algorithm.  Hash.length is its output length.
```

**Comment by kazu-yamamoto** [comment]
OK. Thank you, guys, for your explanations!
