### ISSUE TITLE
Draft format on supported_versions

### ISSUE THREAD

**Issue by alagoutte** [tlswg/tls13-spec#682]
on 4.2.1.1. Draft Version Indicator, it is no indicate the "format" of draft

NSS (Firefox) use draft convert to hex (0x7f0a for draft-16) but new picotls implementation use decimal (0x7f16)

**Comment by ekr** [comment]
This is a list of byte values (cf. DTLS 1.2 version number), so it should be 0x7f0a.

I pushed https://github.com/tlswg/tls13-spec/commit/0353994e038cfbf15becc68c412644789d2e3009 to clarify this point

**Comment by kazuho** [comment]
Thank you for the clarification. I have updated picotls addressing the issue.

**Comment by alagoutte** [comment]
Thanks for (quick) fix/clarification !
