### ISSUE TITLE
Undefined "select" syntax

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#700]
Only one *expression* is allowed after "case" of "select". But after the "client_hello" case, two expressions are enumerated:

```
   struct {
       select (Handshake.msg_type) {
           case client_hello:
              PskIdentity identities<6..2^16-1>;
              PskBinderEntry binders<33..2^16-1>;
              
           case server_hello:
              uint16 selected_identity;
       };

   } PreSharedKeyExtension;
```

We should define one structure to hold both `PskIdentity` and `PskBinderEntry`.

**Comment by martinthomson** [comment]
We can't combine the structures, the line between those two things is where the handshake transcript is truncated when calculating the binders.

I wasn't aware of the rule for one entry after each case.  I thought that it permitted all entries up until the next case statement.

**Comment by ekr** [comment]
Where are you getting the rule that only one value can come after a case?

In any case, as MT says you can't combine the structures. If such a rule exists (which I'm not convinced it does) you would need to do:

struct {
   PskIdentity identities<6..2^16-1>;
    PskBinderEntry binders<33..2^16-1>;
}

**Comment by kazuho** [comment]
I believe the the restriction @kazu-yamamoto is referring to is: _There must be a case arm for **every** element of the enumeration declared in the select_ ([section 3.6.1](https://tlswg.github.io/tls13-spec/#variants)).

**Comment by kazu-yamamoto** [comment]
`struct` in `struct` is not allowed execpt *annoymous struct* (`struct {}`). I believe the presentation language is carefully designed to avoid such a nesting definition.

We should define a top level structure for this.

**Comment by davegarrett** [comment]
We may have stumbled into a prescriptivist vs. descriptivist debate, here. Since our syntax is effectively ad hoc with respect to this document, I'm on the descriptivist side.

The current syntax is fine. If clarifications would help on how we describe that syntax to allow for this case, then that wouldn't be unwelcome. However, we're not writing a machine-readable language here; this is for human consumption, and superfluous notation can just be counter-productive.

**Comment by kazu-yamamoto** [comment]
I'm not on both sides. What I want is just a clear definition. I implemented a parser based on Section 3 but it cannot parse the syntax time to time. It's OK for me to extend the presentation language but I want to avoid usage of non-defined syntax rule.

Note that I could find many syntax errors since the syntax is machine-readable. And basically static analysis tools help productivity.

But if the editor and contributors think this syntax check is counter-productive, I will stop this activity.

**Comment by ekr** [comment]
I do think it's productive to have a clear definition, and having something
that can be mechanically parsed is good. If there are clear inconsistencies
in the syntax as used, I'm happy to fix them, but I think @davegarrett is
basically right in that the defn of the syntax is mostly in the way it's
used, so if there's something that we do a lot and that would be contorted
not to do then we should do it and modify the syntax section to match
(that's mostly how we got case fall-through btw).

Anyway, I don't see a section that forbids the use of multiple struct
elements in a single case branch: the section @kazuho points to says that
there must be an arm for every enum element.

I suggest we resolve this particular item by explicitly allowing the
construct;

select (foo) {
  case A:
     T t1;
  case B:
     T t2;
     U u1;
};

**Comment by kazu-yamamoto** [comment]
OK. I send a pull request to clarify the presentation language. I modified my parser and confirmed that it can parse the current syntax.

**Comment by kazu-yamamoto** [comment]
The patch above has been merged. Let's close.
