### ISSUE TITLE
Extension in NewSessionTicket

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#711]
- `NewSessionTicket` includes `Extension` which means a hello extension.
Is this intentional or should this be `TicketExtension` or something?
- How we can tell the type of `extensions` without `TicketExtensionType`?
- `ticket_extensions` is used in the explanation but not found in this structure. Should we replace `extensions` with `ticket_extensions`?

```
struct {
    uint32 ticket_lifetime;
    uint32 ticket_age_add;
    opaque ticket<1..2^16-1>;
    Extension extensions<0..2^16-2>;
} NewSessionTicket;
```

**Comment by ekr** [comment]
1. I made all extensions the same type. Having a separate type seemed silly.
2. Extension contains a type:
       struct {
           ExtensionType extension_type;
           opaque extension_data<0..2^16-1>;
       } Extension;

3. I actually think s/ticket_extensions/extensions/ as we can say NewSessionTicket.extensions

**Comment by kazu-yamamoto** [comment]
@ekr Thank you for explanation. I sent a pull request to make this easier to understand.

**Comment by kazu-yamamoto** [comment]
The PR has been merged. Let's close.
