### ISSUE TITLE
SNI and 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#720]
The intro mentions that SNI is bound to a PSK.  But later the server is only required to validate version, cipher suite and ALPN.  What gives?

**Comment by ekr** [comment]
Good catch. We changed it but not everywhere.

**Comment by ekr** [comment]
Oh, this is only needed for external PSKs. That's fine.

**Comment by martinthomson** [comment]
So it's OK to resume with a different name in the SNI?  I'm pretty sure that we don't accept that in NSS.

**Comment by ekr** [comment]
The conclusion was that it should be the same for 0-RTT and resumption and David argued to me that it was OK for both (IIRC).

Maybe @davidben can weigh in here.

**Comment by martinthomson** [comment]
If the conclusion was that they should be the same, then why do we insist on binding 0-RTT keys to SNI?

**Comment by davidben** [comment]
I don't know of anyone that resumes across names (although there may be something to be said for doing so with h2). The spec hasn't historically done a good job of saying when you do and don't get to resume. Name isn't sufficient if, say, your application has two different contexts with different client certificate decisions. The discussion in issue #136 tried to touch on this, though it was closed before it got anywhere.

Anyway, I don't think 0-RTT rules are the place for it, one way or another. It seems either both 0-RTT and resumption should be okay or both shouldn't be. 0-RTT has no particular need to constrain client extensions, just like it's perfectly fine to change your ALPN advertisement when you do 0-RTT. The only requirement is what the server selects not change.

**Comment by ekr** [comment]
@martinthomson if you are referring to S 2.3, that really should be in the PSK section, because the requirement is that the client know what SNI to offer.

**Comment by martinthomson** [comment]
Yes, I'm referring to the list in 2.3.  There is a difference between what the client might offer in the handshake (which should reflect what the client is willing to do, nothing else) and what it *binds to the PSK*.  The list in 2.3 says that SNI is bound to the PSK, but I agree with @davidben that that is only really possible if we insist on binding SNI to resumption in general.

**Comment by ekr** [comment]
Yeah, this all got kind of confused.

Right now, RFC 6066 simply forbids resumption across SNI:

"   When the server is deciding whether or not to accept a request to
   resume a session, the contents of a server_name extension MAY be used
   in the lookup of the session in the session cache.  The client SHOULD
   include the same server_name extension in the session resumption
   request as it did in the full handshake that established the session.
   A server that implements this extension MUST NOT accept the request
   to resume the session if the server_name extension contains a
   different name.  Instead, it proceeds with a full handshake to
   establish a new session.  When resuming a session, the server MUST
   NOT include a server_name extension in the server hello.
"

So, this seems like it should also apply to TLS 1.3 and of course also to 0-RTT, but of course the text doesn't say one way or the other (ugh).

If we're considering allowing it (and obviously I kind of thinkoed the text here) we presumably should have some real analysis before we allow it in TLS 1.3, as we know there are risks here:
http://antoine.delignat-lavaud.fr/doc/www15.pdf
