### ISSUE TITLE
minimum required extensions

### ISSUE THREAD

**Issue by kroeckx** [tlswg/tls13-spec#746]
In the Client Hello (4.1.2) it says:
As of TLS 1.3, all clients and servers will send at least one extension (at least "key_share" or "pre_shared_key").

I believe that at least the supported_versions extension is also required for a client.

**Comment by davegarrett** [comment]
Rather than enumerating everything here, I've pushed a PR to just change "at least" to "e.g.".

**Comment by ekr** [comment]
I changed this separately.
