### ISSUE TITLE
Description of confidentiality in ch 1.

### ISSUE THREAD

**Issue by secworks** [tlswg/tls13-spec#749]
Could we rephrase the description of confidentiality in chapter one?

It now reads "Confidentiality: Data sent over the channel is not visible to attackers.". As far as I see it, data, will be visible to anybody that observes the traffic. However it is not possible for an attacker to get the contents, the cleartext meaning of the data. But for example observing the amount of data and that data is flowing over the channel is visible to an attacker.

Something like this perhaps:
Confidentiality: The information in the data sent over the channel is not available to attackers.

**Comment by martinthomson** [comment]
We could be more pedantic and observe that it's not just attackers, it's everyone else.

> The data sent over the connection is only available to the endpoints.

And then maybe add:

> TLS does not hide the length of the data it transmits, though endpoints are able to pad to obscure lengths.

**Comment by secworks** [comment]
Sounds good to me.

**Comment by richsalz** [comment]
> TLS does not hide the length of the data it transmits, though endpoints are able to pad to obscure lengths.

On first reading, I took obscure to be an adjective.  How about "in order to obscure..."

**Comment by secworks** [comment]
Even better.
