### ISSUE TITLE
enumerate all "_RESERVED" values in an appendix table

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#75]
The list of obsoleted values in enums is ever increasing. Minor suggestion for the backwards compatibility appendix E: add a table of all "_RESERVED" values from all enums that are now MUST NOT sends/accepts.

**Comment by ekr** [comment]
We added text about this, and now that we auto-generate these tables, we can just add as many reserved values as we want, so closing. Feel free to produce PRs for missing reserved values
