### ISSUE TITLE
SHA-224 in signature algorithms must be SHA-1

### ISSUE THREAD

**Issue by roelpeeters** [tlswg/tls13-spec#754]
[editorial]
In section 4.2.3. Signature Algorithms it says:
 In particular, MD5 [SLOTH] and SHA-224 MUST NOT be used.
this should be:
 In particular, MD5 and SHA-1 [SLOTH] MUST NOT be used.

**Comment by davidben** [comment]
It's actually SHA-224, confusingly. That text refers to algorithms that were completely removed as of TLS 1.3 and thus applies retroactively to TLS 1.2. Sadly, SHA-1 cannot be taken out of TLS 1.2 just yet. TLS 1.2 messed up catastrophically here. Its ServerKeyExchange SHA-1 default meant a lot of implementations took shortcuts and only sign SHA-1. It will take a lot of ecosystem work to get rid of that one, so a MUST NOT is not realistic right now. :-(
