### ISSUE TITLE
0 for salt

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#784]
In Section 7.1, `0` for input key material (or secret) is 0s of Hash.length.
But `0` for salt is not clearly defined.
If it means 0s of Hash.length, please state it explicitly.

Relating to:

https://github.com/martinthomson/tls13-vectors/issues/2

**Comment by kaduk** [comment]
Do you see the text about:


   If a given secret is not available, then the 0-value consisting of a
   string of Hash.length zeroes is used.  Note that this does not mean
   skipping rounds, so if PSK is not in use Early Secret will still be
   HKDF-Extract(0, 0).

With respect to the start of the chain, the input from the top is the 'salt' input to HKDF-Extract; RFC 5869 says:

```
2.2.  Step 1: Extract

   HKDF-Extract(salt, IKM) -> PRK

   Options:
      Hash     a hash function; HashLen denotes the length of the
               hash function output in octets

   Inputs:
      salt     optional salt value (a non-secret random value);
               if not provided, it is set to a string of HashLen zeros.
      IKM      input keying material

   Output:
      PRK      a pseudorandom key (of HashLen octets)

   The output PRK is calculated as follows:

   PRK = HMAC-Hash(salt, IKM)
```

which is pretty clear about the HashLen of zeros part.  If there was a better way for the diagram to indicate "not provided" for the start of the chain that might be worth doing, but I am not convinced that extra text is really needed.

**Comment by ekr** [comment]
I agree with @kaduk here. Closing

**Comment by kazu-yamamoto** [comment]
OK.
So, we should fix the vector draft.

**Comment by martinthomson** [comment]
I just learned something today.  I will follow up with the CFRG regarding an erratum on RFC 5869.

HashLen is defined as the output size of the hash.  RFC 2104 defines HMAC to take B bytes (B == block size).  That means that we have a potential interop problem if HKDF is ever used with a hash that has a smaller block size than its output size.  It's probably academic, but...

**Comment by martinthomson** [comment]
Yep, it's academic.  HMAC breaks completely if B < L.
