### ISSUE TITLE
Add an appendix containing a set of PRF test vectors

### ISSUE THREAD

**Issue by alexmgr** [tlswg/tls13-spec#796]
Hi,

Knowing if `7.1. Key Schedule` is correctly implemented is difficult without having a set of test data to compare against. For example, `RFC 5869` provides a `Appendix A.  Test Vectors` section, which allows to trivially check the implementation.
Today, in order to know if key derivation is correct, one has to implement encryption/decryption fully. It would be helpful to have a set of PRF inputs and expected outputs to be able to validate against.

As a side note, If anyone which has implemented TLS 1.3 could provide such test vectors, it would be useful to me at least ;)

Thanks

**Comment by kaduk** [comment]
See https://tools.ietf.org/html/draft-thomson-tls-tls13-vectors-00

**Comment by alexmgr** [comment]
Perfect! Thank you.
