### ISSUE TITLE
Format of Supported Versions Extension

### ISSUE THREAD

**Issue by Eichhoernchen** [tlswg/tls13-spec#823]
Hi,

the current draft illustrating the Supported Versions Extension differs from the actual implementations in Chrome and [NSS.](https://hg.mozilla.org/projects/nss/annotate/tip/lib/ssl/tls13exthandle.c#l899)
This is currently specified:

      struct {
          ProtocolVersion versions<2..254>;
      } SupportedVersions;

Yet, Chrome Version 57.0.2953.0 (Official Build) canary (64-bit) sends the following:

      struct {
          uint8 len_bytes;
          ProtocolVersion versions<2..254>;
      } SupportedVersions;

Here is an except from a packet dump:
`00 2b | 00 0b  | 0a |  8a 8a | 7f 12 | 03 03 | 03 02 | 03 01`
`TLS Ext: 43 | Ext Len: 11 | ?len?: 10 | random_version | draft-18 | tlv 1.2 | tls 1.1 | tls 1.0`

I do get the random_version thing to test the other sides version negotiation, but what is that second len field for?
Are the specs wrong or is the implementation wrong?
Imho it does not make sense to send the length twice, why limit the length to 256 bytes? okay this is kind of given by the draft but why do so via an 8-bit field?

Thanks

**Comment by ekr** [comment]
Chrome is correct (and matches the spec).

The outer four bytes are the extension type and length. The inner length byte is the length of the vector itself.

**Comment by Eichhoernchen** [comment]
How does it match the specs? The specs don't say anything about sending the length of the vector.
And it is kind of unnecessary, the extension length would be exactly the length of the vector if one would not send the length of the vector... I would kind of get if it were the number of versions i.e. bytes/2 but this seems not right :)

**Comment by ekr** [comment]
> How does it match the specs? The specs don't say anything about sending the length of the vector.

https://tlswg.github.io/tls13-spec/#vectors
```
Variable-length vectors are defined by specifying a subrange of legal lengths, inclusively, using the notation <floor..ceiling>. When these are encoded, the actual length precedes the vector’s contents in the byte stream. The length will be in the form of a number consuming as many bytes as required to hold the vector’s specified maximum (ceiling) length. 
```

> And it is kind of unnecessary, the extension length would be exactly the length of the vector if one would not send the length of the vector...

Yes, it is unnecessary. It's an artifact of the presentation language. That's just how vectors are represented. You could do something different, but it's clunky to write and doesn't let fields be self-contained in your decoder.

> I would kind of get if it were the number of versions i.e. bytes/2 but this seems not right :)

In TLS the length bytes is the length of the field, not the number of entries. This is a persistent source of confusion, unfortunately, but we're stuck with it.

**Comment by Eichhoernchen** [comment]
Oh boy... thank you so much, sorry for bothering, I really did not find that part in the specs and I started to wonder and question so many things...
