### ISSUE TITLE
remove legacy_record_version in TLSCiphertext?

### ISSUE THREAD

**Issue by mimoo** [tlswg/tls13-spec#855]
Any reason to keep the `legacy_record_version` field in the `TLSCiphertext` structure? ([see here](https://tlswg.github.io/tls13-spec/#record-payload-protection)).

It looks like this could be safely removed and allow us to release 6 lines in that long spec =)

**Comment by ekr** [comment]
Please see PR#762. I am planning to run an experiment in the next few weeks to see if it is safe to land.

**Comment by ekr** [comment]
I'm closing this as a duplicate.
