### ISSUE TITLE
A broken syntax of  EarlyDataIndication

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#861]
The current syntax of `EarlyDataIndication` is broken because case arms must be terminated by `;`.

```
    struct {
       select (Handshake.msg_type) {
           case new_session_ticket:
              uint32 max_early_data_size;

           case client_hello:
           case encrypted_extensions:
              // empty
       };
   } EarlyDataIndication;
```

If we respect to TLS 1.2's syntax, I would suggest to change this into:

```
    struct {
       select (Handshake.msg_type) {
           case new_session_ticket:
              uint32 max_early_data_size;

           case client_hello:
           case encrypted_extensions:
              struct {};
       };
   } EarlyDataIndication;
```

**Comment by mimoo** [comment]
1. I think this is more confusing than the `// empty`. The presentation language is not a formally specified syntax so I don't think it matters.

2. I remember tripping while reading this part of the specs because of the two cases following each other, I would rather replace them by this:

```
case client_hello:
    // empty
case encrypted_extensions:
    // empty
```

**Comment by richsalz** [comment]
I don't like the comment, I'd rather have a syntactic token there and I don't care what it is.

**Comment by mimoo** [comment]
What about just removing the cases for `client_hello` and `encrypted_extensions`?

**Comment by richsalz** [comment]
Don't care. :)  Just don't want comments to be semantically meaningful.

**Comment by kaduk** [comment]
Removing the cases is wrong, as then it leaves unspecified a structure that needs to be sent in a wire protocol message.

**Comment by kazu-yamamoto** [comment]
`struct {}` is actually used to express empty in RFC 5246.
Let's just define its semantics in Section 3.

But I recommend most is to define `Empty`:

```
    struct {} Empty;

    struct {
       select (Handshake.msg_type) {
           case new_session_ticket:
              uint32 max_early_data_size;

           case client_hello:
           case encrypted_extensions:
              Empty;
       };
   } EarlyDataIndication;

```

**Comment by mimoo** [comment]
Any other opinions on this? Possibilities I see:

* an `empty` field could be defined in the presentation language → but it's more text to the presentation language for few usages
* the text in the presentation language about cases that must cover all the cases could be relaxed → but now that I think more about it, it's nicer for the implementer to see all the cases in this snippet
* this `struct {} Empty;` could be defined  → I don't like it so much, I think a more casual `// empty` is actually clearer.

This makes me thing we should probably drop this issue.

**Comment by kazu-yamamoto** [comment]
How about this?

```
case client_hello: ; // empty
case encrypted_extensions: ; // empty
```

P.S. Fall through is not used in other parts.

**Comment by mimoo** [comment]
It looks good to me, also if fall through is not used anywhere else it could be removed from the presentation language section.

**Comment by kazu-yamamoto** [comment]
"Fall-through" was added in TLS 1.2. We can copy-and-pase Section 4.6.1 of RFC 4346 to remove fall-through.

If this is consensus, I will make a PR.

**Comment by kazu-yamamoto** [comment]
I've sent PR #877.
