### ISSUE TITLE
self-signed certificates not validated?

### ISSUE THREAD

**Issue by roelpeeters** [tlswg/tls13-spec#869]
In section 4.2.3. Signature Algorithms:
> The signatures on certificates that are self-signed or certificates that are trust anchors are not validated since they begin a certification path (see [RFC5280], Section 3.2). 

While it make sense not to validate the signatures on the certificates that are trust anchors, why would one not check the signature on a self-signed certificate? Also the reference that is to serve as justification seems to be wrong: [RFC5280], Section 3.2 points to a section on the keys of EdDSA.

**Comment by martinthomson** [comment]
A self-signed certificate is nothing more than a complicated key container when it comes down to it.  It's good hygiene to have a valid signature, but nothing depends on it.

https://tools.ietf.org/html/rfc5280#section-3.2 looks like the right place to reference to me.  It is entitled "Certification Paths and Trust".  The text means "Section 3.2 of [RFC5280]", I'll admit that it's a cumbersome construction though.

**Comment by roelpeeters** [comment]
surely it must have value, otherwise why must certificates that start a certification path be signed in the first place? or do you mean that this is outside the scope of TLS and it is up to user whether or not to verify these signatures on certificates that start the certification path?

My bad, I had two rfc's open and I looked at the wrong one.

**Comment by martinthomson** [comment]
All I can really say for sure is that TLS does not rely on the signature in the certificate.  As far as it goes, pretty much nothing in a self-signed certificate other than the public key is useless in most cases.

I don't know why X.509 requires a self-signature, other than to fill the signature slot for consistency with certificates that have non-pointless signatures.  Of course, I am not familiar with all the potential uses for certificates or the development of X.509.

**Comment by ekr** [comment]
In any case, cert evaluation is out of scope for TLS. The purpose of this
text is just to exclude trust anchors from the algorithm restriction

**Comment by mimoo** [comment]
I agree with above, the signature in a self-signed certificate is not useful information.

**Comment by ekr** [comment]
I don't believe any change is needed here.
