### ISSUE TITLE
The Pseudorandom Function

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#87]
This section says "This PRF with the SHA-256 hash function is used for all cipher suites defined in this document ". This was valid in RFC 5246 because it defines TLS_XXX_SHA256 (or weaker) only. However, this draft also defines TLS_XXX_SHA384 resulting in a contradiction. I think this sentence should be rephrased.

**Comment by davegarrett** [comment]
@ekr: This can be closed now.

This was dealt with at some point, probably in the HKDF merge.

**Comment by kazu-yamamoto** [comment]
Right. Let's close.
