### ISSUE TITLE
Guidance on ticket renewal cliff

### ISSUE THREAD

**Issue by davidben** [tlswg/tls13-spec#871]
This is somewhat application-dependent, but ticket-based PSKs with certificate-based auth are by far the most common use of TLS, and this is not immediately obvious: we should include guidance on ticket lifetimes. Specifically, a ticket issued from a resumed connection should take into account the freshness of any CertificateVerify signature being carried over. This will probably translate to a non-renewable lifetime on sessions.

**Comment by martinthomson** [comment]
In other words, you can keep resuming from resumed sessions, but only up to the point that the original authentication remains valid.

**Comment by mimoo** [comment]
you can also keep replaying 0-RTT up until that point.

**Comment by davidben** [comment]
@mimoo I think that's orthogonal? 0-RTT replay is bound by the server's ticket_age tolerance and the lifetime on the *server* for that *particular* ticket. If the ticket is renewed, you get a fresh ticket, so it wouldn't affect 0-RTT. This is about lifetime on the *client* (or server in case of client certs) of renewed tickets.

Am I missing something?

**Comment by mimoo** [comment]
Yeah you are right.

So I thought you were talking about how long should a client hold on to a ticket (which is upper bounded by how long the server wants it to be valid (which should be heavily influence by how long it thinks it's OK for that ticket to be replayed)). But instead you're talking about how long, or how many times should a client limit itself to resume from a resumed session correct?

**Comment by davidben** [comment]
"Session" is a little overloaded, so I'm not sure what you mean. This commit message might help:
https://boringssl.googlesource.com/boringssl/+/17b30833737b32ecab1f12c105e1b5cae6d49458

**Comment by kaduk** [comment]
>  But instead you're talking about how long, or how many times should a client limit itself to resume from a resumed session correct?

For "session" defined as something that encompasses multiple TLS connections all using tickets that chain back to the same initial handshake [with client authentication] with no subsequent occasions where the client certificate is presented, yes.  Though, I don't think there's much reason to limit by number of tickets; wall clock time seems to be the main concern.

**Comment by ekr** [comment]
@davidben: maybe something like this in S 4.6.1 after we describe the 7 day limit.

"In principle, it is possible to continue issuing new tickets which continue to indefinitely extend the lifetime of the keying material originally derived from an initial non-PSK handshake (which was most likely tied to the peer's certificate). It is RECOMMENDED that implementations place limits on the total lifetime of such keying material; these limits should take into account the lifetime of the peer's certificate and the likelihood of intervening revocation."

**Comment by davidben** [comment]
Sounds reasonable. I'd suggest explicitly mentioning the lifetime of the CertificateVerify signature. One might, say, re-verify the certificate on resumption, but that wouldn't quite resolve the issue.

**Comment by martinthomson** [comment]
If, by which, you mean "...in the time since the peer last proved that it controls the private key corresponding to its certificate", I agree that's the relevant factor.

**Comment by ekr** [comment]
What do you mean "lifetime of the CertificateVerify" signature? There's no explicit lifetime there, AFAIK.

**Comment by davidben** [comment]
I thought that was the whole point of this exercise and all the 0-RTT + certs musings. That we don't want to indefinitely reuse that signature. Though, yeah, there isn't an explicit lifetime. I think it's fine for that to be local policy.

**Comment by ekr** [comment]
@davidben: I think we agree on the facts and what people should do, I'm just trying to figure out what you want changed about my text.

**Comment by davidben** [comment]
Perhaps: "these limits should take into account the lifetime of the peer's certificate, the likelihood of intervening revocation, and the time since the peer's online CertificateVerify signature."

The old text suggests that, if I were to retain the certificate chain on resumption and re-check expiration plus perhaps an online revocation check, I'm all good for indefinite lifetimes.

**Comment by ekr** [comment]
Got it. Willdo.
