### ISSUE TITLE
Exporter label requirements

### ISSUE THREAD

**Issue by jsalowey** [tlswg/tls13-spec#872]
refer the reader to exporter requirements in RFC 5705

"Requirements for the format of Exporter labels are defined in section 4 of RFC5705."

Creating pull request.

**Comment by ekr** [comment]
@jsalowey: should we expect a PR?

**Comment by ekr** [comment]
This appears to be done.

**Comment by jsalowey** [comment]
yes I submitted PR #874 which has been merged already.
