### ISSUE TITLE
Proof of work for DoS mitigation

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#9]
Providing proof of ownership at a server is a non-trivial computational burden.  If a server was able to request that a client submit proof of work, then a loaded server could use this to help separate DoS attackers from genuine clients.

**Comment by ekr** [comment]
This seems like a good idea, but I don't think it needs to be in 1.3. We've talked about an extension and we could do that for 1.x

**Comment by enygren** [comment]
Sample proposal for how this could be handled as an extension utilizing HelloRetryRequest:
https://tools.ietf.org/html/draft-nygren-tls-client-puzzles-00

(although updates are needed to that based on feedback received, as well as to update to incorporate HelloRetryRequest hash continuation changes)

**Comment by martinthomson** [comment]
I think that we would need to have `HelloRetryRequest` support extension.  I don't think that we discussed that option at all.  It adds to the potential modifications that might be made to the `ClientHello`, which is hazardous.  Something for us to keep in mind in the stateless reject work.

**Comment by enygren** [comment]
In draft-ietf-tls-tls13-10, HelloRetryRequest does have an extensions field:

     struct {
          ProtocolVersion server_version;
          CipherSuite cipher_suite;
          NamedGroup selected_group;
          Extension extensions<0..2^16-1>;
      } HelloRetryRequest;

It may be that only extensions sent back in a HelloRetryRequest can be ones that can be modified by the client when they resend ClientHello (and must be registered as such) and any implementation of stateless reject must be able to handle this?  Proof-of-work / ClientPuzzles end up being a generalization of cookie state but where a puzzle response is sent in addition to echoing the cookie.
