### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#906]
@ekr Would you push tags for ID 18 and ID 19?
I would like to see the difference based on the tags.

**Comment by ekr** [comment]
Unfortunately, I forgot to tag -18 so the tag is approximate. The -19 tag is correct. You can use rfcdiff to diff the IDs.

**Comment by kazu-yamamoto** [comment]
I don't see the tags on github.
I guess that you created the tags locally but forgot to push with `--tags`.

**Comment by ekr** [comment]
You're right, I pushed them to my repo but not to master. They should be on master now, but as noted, the -18 tag is only approximate.

**Comment by kazu-yamamoto** [comment]
Thank you! I got the tags!
