### ISSUE TITLE
Contributor middle initials get an extra space

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#907]
Noticed while reading through the diff between the latest drafts.

This is an odd very minor issue showing in the rendered version. See the Contributors section:
https://tools.ietf.org/html/draft-ietf-tls-tls13-19#appendix-G

Now, see the listings for Steven M. Bellovin and David M. Garrett. The two of us have 'M' middle initials listed for our credits, and for some reason an extra space gets added after the period before the last name.

The actual MD file does not have these extra spaces:
https://raw.githubusercontent.com/tlswg/tls13-spec/d329bc5e799221d42ee4a7f55a90460000613244/draft-ietf-tls-tls13.md

This is a little odd. Something somewhere is ever so slightly mangling our names' text.

**Comment by kaduk** [comment]
Seems likely to be the consequence of a "dumb" script applying a two-spaces-after-full-stop policy.
I wouldn't worry about it until AUTH48.

**Comment by ekr** [comment]
We'll let RFC Ed fix this.
