### ISSUE TITLE
Clarification: should ticket_age_add be different for each ticket.

### ISSUE THREAD

**Issue by tmthrgd** [tlswg/tls13-spec#913]
I've spotted a difference between draft implementations of TLS1.3 in the wild and the specification isn't clear as to the required behavior.

Cloudflare's [tls-tris](https://github.com/cloudflare/tls-tris) implementation [reuses the same random ticket_age_add for multiple tickets](https://github.com/cloudflare/tls-tris/blob/911840a4013f4f57b3bd9475a724a4703a64c7dc/13.go#L568-L583), while [BoringSSL](https://boringssl.googlesource.com/boringssl)'s TLS1.3 implementation [uses a different random ticket_age_add for each ticket](https://github.com/google/boringssl/blob/cfb9d147bb8df5dd8b5b5f3d3ec04cf13077d677/ssl/tls13_server.c#L648-L651).

Based on my understanding of ticket_age_add, the value should be unique per ticket to have the desired effect - I could well be wrong though. Either way, it seems the specification needs to be clearer about this. I suggest that this be clarified by explicitly stating whether ticket_age_add may be reused [in section 4.6.1](https://github.com/tlswg/tls13-spec/blob/d55c542ce89b35b317a2f2e1af405382c66ed01f/draft-ietf-tls-tls13.md#new-session-ticket-message-newsessionticket).

**Comment by kaduk** [comment]
It should be unique per ticket.  But, I guess we ought to add more text, given the observed behavior.
