### ISSUE TITLE
Clarifying replay properties

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#919]
It is hard to understand the current text of Section 4.2.9.3 (Replay Properties).
@kazuho explained me that a server should check:

```
(server_recv_time - server_send_time) - (client_send_time - client_recv_time) < RTT + delta
```

The server can tell:
- server_recv_time == now
- server_send_time == one parameter in the ticket
- client_send_time - client_recv_time == ticket_age == obfuscated_ticket_age + ticket_age_add

If this understanding is correct, I would suggest to add more explanation to the section.

**Comment by ekr** [comment]
Yes, that's correct. PRs welcome

**Comment by kaduk** [comment]
I made a tweak to avoid referring to the "base value", in #936, though more changes may still be helpful.
