### ISSUE TITLE
Write a new reader friendly changes section

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#923]
Posting an issue so this gets explicitly tracked, as it's come up on the mailing list a few times recently.

The "Major Differences from TLS 1.2" section evolved over the development time to be a full changelog, including changes from draft to draft. We need a new, fully fleshed-out, "Major Differences from TLS 1.2" section that covers this stated topic concisely and is written for a new reader of this document, rather than someone who's followed its development.

**Comment by ekr** [comment]
Yes, I'll write something.
