### ISSUE TITLE
Have a range of permitted unsolicited values in HRR

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#939]
Right now, only Cookie can be unsolicited in HRR, but maybe we would want to add other things which is basically impossible now. Nikos suggested allowing anything or having a range.

**Comment by davidben** [comment]
What would a client do in response to an unknown unsolicited field? Ignoring extensions in HRRs doesn't typically work (plus that means it is an optional feature and could be negotiated in the usual way). Cookie is this weird thing where we allowed it unsolicited just to make it MTI, but we can't just add new MTI extension after the fact.

**Comment by ekr** [comment]
Yeah, this is a good point.

**Comment by martinthomson** [comment]
An alternative, though perhaps not a great one, is to require that clients include cookie in every handshake. One reason that it might be bad is that it is an extension that has had a definition for some time, and that definition never required inclusion in ClientHello, or in TLS (just DTLS). That could trigger a whole new class of intolerance.

**Comment by ekr** [comment]
Yeah, seeing no enthusiasm for a change here. Closing
