### ISSUE TITLE
Warn against low entropy PSKs

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#965]
The binder makes it trivial to dictionary attack the PSK

**Comment by hannestschofenig** [comment]
I think it would be useful to add a short note to Section 2.2. 

Something like this paragraph would do the job: 
"Note: When using an out-of-band provisioned pre-shared secret, a critical consideration is using sufficient entropy during the key generation, as discussed in [RFC4086].  Deriving a shared secret from a password or other low-entropy sources is not secure. A low-entropy secret, or password, is subject to dictionary attacks. The specified PSK authentication is not a strong password-based authenticated key exchange even when used with a Diffie-Hellman exchange."
