### ISSUE TITLE
"Updating Traffic Keys and IVs" section lists generic label for both client & server

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#966]
https://tools.ietf.org/html/draft-ietf-tls-tls13-19#section-7.2
https://tlswg.github.io/tls13-spec/#updating-traffic-keys

Currently, we generically specify how to generate application_traffic_secret_N+1, and it uses the label "application traffic secret". Everywhere else we explicitly state separate client/server values/labels or use a "[sender]_" prefix. It should probably be something like this, instead:

client_application_traffic_secret_N+1 =
        HKDF-Expand-Label(client_application_traffic_secret_N,
                                         "client application traffic secret", "", Hash.length)
server_application_traffic_secret_N+1 =
        HKDF-Expand-Label(server_application_traffic_secret_N,
                                         "server application traffic secret", "", Hash.length)

(or, use a "[sender]_" prefix and maybe list both labels with an "|" as done elsewhere, but that feels more complicated for no real reason)

Also, all the "client_/server" prefixes in this section's text should probably be simplified to "[sender]_" prefixes.

Posting as an issue first rather than PR as this would change labels and be an effective wire-format change.

**Comment by davidben** [comment]
Getting rid of some of the repeated client/server splits was an explicit goal (though not the primary one) of splitting up the key schedule ladders and some of the other key schedule tweaks around that time. The two schedules are already split at this point and it's a place where we'd needlessly check is_client/is_server send/receive. Same reason why the key/IV labels are just "key" and "iv" at this point. It seems small, but, having worked on an implementation, it's a significant complexity win.

**Comment by davegarrett** [comment]
If we're ok with using the same label for both client & server key updates, it should probably be labeled something explicit and not something that could be mistaken for other labels, e.g. simply "secret update" or something. (similar to how we've got just "key" and "iv")

**Comment by ekr** [comment]
I'm not seeing much of an issue here, but if we end up shrinking the labels as in #964, I would be willing to take a look.
