### ISSUE TITLE
Three phases in the TLS handshake (Figure 1)

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/tls13-spec#968]
Figure 1 "Message flow for full TLS Handshake" classifies different TLS messages to three phases, key exchange, server parameters, and authentication. While this sounds useful it does not take the more recent developments around PSK-based authentication into account. For example, the ClientHello is labeled as a key exchange message while with PSK it also performs authentication since the pre_shared_key extension contains the binder value. 

My suggestion is to remove the labels from the figure. The text that talks about the different phases is still consistent with the rest of the document.

**Comment by ekr** [comment]
I tend to think this is still useful, so absent wild outcry I'm going to leave this as-is.
