### ISSUE TITLE
Information to be provisioned with out-of-band PSKs

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/tls13-spec#969]
Section 2.2 says: 
"
When PSKs are provisioned out of band, the PSK identity and the KDF to be used with the PSK MUST also be provisioned.
"

Section 2.3 

"
When clients use a PSK obtained externally to send early data, then the following additional information MUST be provisioned to both parties:
- The cipher suite for use with this PSK
- The Application-Layer Protocol Negotiation (ALPN) protocol, if any is to be used
- The Server Name Indication (SNI), if any is to be used
"

I believe the two sections should say the same. Ideally, the text should better be included in Section 4.2.10 "Pre-Shared Key Extension", which already talks about associating the PSK with a hash algorithm. 

Note that the term ciphersuite in Section 2.3 refers to the hash/KDF used in Section 4.2.10 and Section 2.2.

**Comment by kaduk** [comment]
Note the "additional" in section 2.3's text.  There really are extra restrictions when you want to use early data, since negotiation is not possible.

**Comment by hannestschofenig** [comment]
I am just suggesting to move the following text from Section 2.3 into Section 4.2.10:

"When clients use a PSK obtained externally to send early data, then the following additional information MUST be provisioned to both parties:
- The cipher suite for use with this PSK
- The Application-Layer Protocol Negotiation (ALPN) protocol, if any is to be used
- The Server Name Indication (SNI), if any is to be used
"

The other security warnings about the zero-RTT exchange make sense in Section 2.3

**Comment by kaduk** [comment]
Okay, the 

> I believe the two sections should say the same

had me thinking that you wanted the same restrictions to apply to early data and regular application data.

I don't object to moving the normative restrictions to the section specific to the PSK extension, though my preference would be to leave them as-is -- the extension is used for both NST-provisioned and externally-provisioned PSKs, and it might be clearer to call out these specific restrictions in the section specific to the external provisioning.  One could argue that it would be okay in the replay properties sub-section (4.2.8.3 in the draft-19 numbering), but it feels a little off-topic to me there, too.

**Comment by ekr** [comment]
I agree with @kaduk about this, and I think it's editorial discretion, so closing.
