### ISSUE TITLE
Table of key derivation labels

### ISSUE THREAD

**Issue by kaduk** [tlswg/tls13-spec#973]
Looking through the minutes from Chicago, there was mention of having a table for the various labels used in key derivation.  Did we want that in this document, or should we shunt it off to something of broader scope?

**Comment by ekr** [comment]
I'm not opposed to it, but it's not clear to me how it would help either. Does someone want to propose something so I can see what it would look like?

**Comment by ekr** [comment]
I don't think this is ultimately necessary, so marking it parked, soon to be closed.
