### ISSUE TITLE
combine DSS,RSA,ECDSA part of ciphersuites to CERT?

### ISSUE THREAD

**Issue by nmav** [tlswg/tls13-spec#98]
Currently in TLS 1.2 there are ciphersuites which specify in addition to their key exchange the algorithm in the certificate. This provides a strict control on the algorithm possibilities, but no flexibility when a new signature scheme comes up, since a new bunch of ciphersuites must be defined. For example, one cannot use AES-CCM with ECDHE and RSA certificates, while it can use it with ECDHE and ECDSA certificates (RFC7251), or DHE and RSA certificates, even though there is no security reason for prohibiting the former. In fact so far there hasn't been a reason to allow a signature algorithm with a specific key exchange, but forbid it with an other one.

Wouldn't it be simpler and more flexible instead of having:
TLS_DHE_(DSS)_WITH_AES_128_CBC_SHA1
TLS_ECDHE_(RSA)_WITH_AES_128_CBC_SHA1
TLS_ECDHE_(ECDSA)_WITH_AES_128_CBC_SHA1

to have:
TLS_DHE_(CERT)_WITH_AES_128_CBC_SHA1
TLS_ECDHE_(CERT)_WITH_AES_128_CBC_SHA1

where the allowed algorithms in the PKIX part will defined but not restricted if the security parameters of the certificate algorithm match the ones of the session? That would simplify implementations, and would also fit the signatureAlgorithms extension design, as one despite the generality of CERT, a server could select a certificate that matches the client allowed algorithms.

**Comment by ekr** [comment]
Per meeting in Dallas, I don't think we're going to do this absent a more compelling proposal. Closing for now. Please feel free to reraise with a complete proposal

**Comment by nmav** [comment]
@ekr what does complete proposal mean? I don't see any information on the minutes on what is missing.

**Comment by ekr** [comment]
This doesn't reflect any decision taken in Redmond, I'm just cleaning up the queue.

It's been a while since Dallas but IIRC people weren't that happy with all the
a la carte mechanisms and the guidance was to go back and try to accommodate
the concerns people had raised on-list and in-meeting. You'd have to consult
the video and/or the text minutes.
