### ISSUE TITLE
Discussion of updated and obsoleted RFCs inIntroduction

### ISSUE THREAD

**Issue by jsalowey** [tlswg/tls13-spec#982]
ID-nits complains that we do not include this in the abstract.  We should include in the abstract or introduction.

**Comment by kaduk** [comment]
Somehow I thought it was abstract *and* introduction.

**Comment by seanturner** [comment]
The IESG was at one time adamant that it be in the abstract.  I'm unsure this is still the case, but simply including "This document obsoletes RFCs 5077 and 5246 and updates RFCs 4492, 5705, 6066 and 6961" should appease them.  I'm unsure if the ID Nits will like that or if it wants RFC 5077, RFC 5246, etc. but if the list is there there's should be no complaints from the IESG.

**Comment by ekr** [comment]
Abstract is stupid. Let's let IESG push back

**Comment by seanturner** [comment]
Agreed 💯 I much prefer the new shorter and sweeter abstract.
