### ISSUE TITLE
Reserved values for HashAlgorithm and SignatureAlgorithm registries

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#991]
Is it strictly necessary to include the following in the TLS1.3 draft:

    Finally, this document obsoletes the TLS HashAlgorithm
    Registry and the TLS SignatureAlgorithm Registry, both
    originally created in [RFC5246]. IANA [SHALL update/has
    updated] the TLS HashAlgorithm Registry to list values
    7-223 as “Reserved” and the TLS SignatureAlgorithm
    Registry to list values 4-223 as “Reserved”.

If this text wasn't in the TLS1.3 draft everything would be fine right?  If that's the case, then this text from s10 should be moved to [draft-ietf-tls-iana-registry-updates](https://github.com/tlswg/draft-ietf-tls-iana-registry-updates).

**Comment by ekr** [comment]
Sorry, I'm not following the issue. I'm happy to move it out, though.

**Comment by kaduk** [comment]
It kind of seems like the move of registries should be done atomically, which is ~guaranteed by doing it in the same document, but could still be done atomically if the two documents are advanced at the same time.
(I, like ekr, am not really clear on what the issue is, though.)

**Comment by seanturner** [comment]
I guess I see reserving the remaining values as essentially slamming the door on future assignments.  Was that the intent?

spt

**Comment by seanturner** [comment]
I should have also added that https://github.com/tlswg/draft-ietf-tls-iana-registry-updates already includes a paragraph indicating that Compression Method Identifiers, HashAlgorithm, and SignatureAlgorithm are obsoleted by TLS1.3; adds a note to the registries indicating as much.

spt

**Comment by kaduk** [comment]
My understanding was that yes, "don't look here, go look over there" was the idea.  Any new allocation would need to go in the SignatureScheme registry, regardless of whether it also ended up in the HashAlgorithm or SignatureAlgorithm registry as well for someone's convenience.  Since you have to go to the new registry anyway, it doesn't seem like there would be value in also adding it to the old/deprecated registry.

**Comment by seanturner** [comment]
Okay that makes sense and it explains why the values in the Compression Method Identifiers isn’t also “reserved”.

I guess I’m off the mind that this para could safely be move to the IANA draft.

**Comment by seanturner** [comment]
Specially move the text to s13 of [draft-ietf-tls-iana-registry-updates](https://tlswg.github.io/draft-ietf-tls-iana-registry-updates/#rfc.section.13).
